### ISSUE TITLE
Extensions IExtensionContext in my website

### ISSUE THREAD

**Issue by darkban** [GENERALBYTESCOM/batm_public#112]
Hi guys I saw in the last update that you have implemented the Extensions IExtensionContext and I had been waiting a long time for such a function can you please tell me how I can implement it on website

Extensions: Added ability to create sell transaction from extension via IExtensionContext
Extensions: Added ability to obtain terminal cash information from extension via IExtensionContext

**Comment by generalbytes** [comment]
It is a too broad question. Please elaborate more on "tell me how I can implement it on website". Describe what you want to achieve.
