### ISSUE TITLE
Add ERC20 Coin to the ordered BATM classic 

### ISSUE THREAD

**Issue by Raphael0792** [GENERALBYTESCOM/batm_public#121]
Please add ERC20 coin to the BATM classic ordered order no. PI181180777  and pair the coin with 365.stream exchange

https://github.com/hashbx/token-distribution

**Comment by rpanak-generalbytes** [comment]
We don't have the resources to implement support for every single coin/token out there. For this reason, we have made it possible for you to implement support on your own. Many people already created pull requests and we have merged their code. If you create a PR and it passes code review, your implementation will get merged as well.
