### ISSUE TITLE
Update XChange Library

### ISSUE THREAD

**Issue by claus235** [GENERALBYTESCOM/batm_public#122]
How do I know if the new version has been updated with the latest version of the XChange Library (https://github.com/knowm/XChange)?

**Comment by rpanak-generalbytes** [comment]
You can take a look at the XChange version in the dependency specifications in our [build.gradle](https://github.com/GENERALBYTESCOM/batm_public/blob/master/server_extensions_extra/build.gradle).

**Comment by ztnark** [comment]
I've created a pull request to update XChange, as we also need a newer version for client machines.

**Comment by rpanak-generalbytes** [comment]
@ztnark It not as easy. I've provided more details in the PR (#146).

**Comment by rpanak-generalbytes** [comment]
Done, closing.
