### ISSUE TITLE
Querying transactions and identities in IExtensionContext

### ISSUE THREAD

**Issue by jdebski7** [GENERALBYTESCOM/batm_public#133]
Hello,

Do you have any plans to add functions for querying transactions and identities as like as findAllTerminals method? It would be very useful, especially with arguments like count, offset, sort and order. For now getting such data is pretty problematic because _remoteOrLocalTransactionId_ and _publicIdentityId_ / _phoneNumber_ (for _findTransaction_ and _findIdentity_) can be possessed only by _ITransactionListener_.

**Comment by generalbytes** [comment]
Propose the method signature and we will evaluate it.

**Comment by jdebski7** [comment]
In the most basic methods:

```
List<ITransaction> getTransactionsInProgress()
List<ITransaction> getTransactionsByIdentity(String publicIdentityId)
List<IIdentity> getIdentitiesAwaitingRegistration()
```

Plus maybe IIdentityListener working like ITransactionListener.

And for more complex querying:
```
Integer getTransactionsCount()
List<ITransaction> getTransactions(Integer count, Integer offset)
Integer getIdentitiesCount()
List<IIdentity> getIdentities(Integer count, Integer offset)
```
 
or also with filtering by e.g. atmSerialNumber, type, status etc.

**Comment by chrisrico** [comment]
I'd also like to propose some identity related signatures. One or more of the following:
```
List<IWatchlistMatch> queryWatchlist(IIdentity identity)
List<IWatchlistMatch> queryWatchlist(String publicIdentityId)
List<IWatchlistMatch> queryWatchlist(String firstName, String lastName)
```
The primary use case of this is to query existing identities in bulk each month, so this method could also be useful if there is a non negligible fixed cost of the method call:
```
List<IWatchlistMatch> queryWatchlist(List<IIdentity> identities)
```

**Comment by generalbytes** [comment]
This was added today and will be released next week
List<ITransactionDetails> findAllTransactionsByIdentityId(String publicIdentityId);
List<IIdentity> findAllIdentitiesByState(int state);
WatchListResult searchWatchList(WatchListQuery query);
