### ISSUE TITLE
Integration of exchange

### ISSUE THREAD

**Issue by PatrycjaFTO** [GENERALBYTESCOM/batm_public#143]
Hello,

I am interested in integration of exchange support for FuturoCoin (FTO) 
and ATM.

FuturoCoin is available on many exchanges but not on those you support. 
What should be done to add ATM - FTO exchange integration?

1. If FTO will be available on any of supported exchanges is it enough 
for ATM owners to configure their machine for buying and selling  on 
exchange?

2. Can we implement support for any exchange which lists our coin, e.g. 
Coindeal.com and pull request? Additionaly we are on the way  to add  
FTO to Bitforex or Coinbene.

**Comment by rpanak-generalbytes** [comment]
Hi @PatrycjaFTO,

you need to implement the `IExchange` interface. It is not required for the bare minimum coin support. It it's missing, however, some convenience features are not present on our server.

1. It's not enough. All the exchange implementations must declare what currencies they support. So after FTO is added to e.g. Kraken (which is already supported), you have to change the Kraken support code to handle FTO. In some cases, this is as trivial as just adding it to the declaration of supported currencies. In others, it requires some code changes.

2. Sure you can. Take a look at `IExchange`, that's the interface you need to implement. The repository has plenty of source code of other exchange implementations for you to look at.

**Comment by PatrycjaFTO** [comment]
Hi @rpanak-generalbytes , 
Could you provide us with example of source code of implementation for Kraken exchange? Here or privately if you prefer, as we can not find it anywhere.

**Comment by rpanak-generalbytes** [comment]
I used Kraken only as an example. Its implementation is not part of the public source code. There are plenty of others, though. Import the GitHub java project into a Java IDE and take a look at `IExchange` implementations.

**Comment by rpanak-generalbytes** [comment]
@PatrycjaFTO I'm closing this issue, as I think you have all the information needed. Feel free to reopen if needed.
