### ISSUE TITLE
[question] BATM/CAS extension integration verification

### ISSUE THREAD

**Issue by jpbriquet** [GENERALBYTESCOM/batm_public#151]
Hello,

I'm currently evaluating the amount of development needed to create an extension (e.g. new cryptocurrency addition, new exchange, new rate source, …) and have some questions about how to verify such integration within your application.

The Tester tool that you provide is handy to verify each element independently but I've seen no way to test the whole integration (BATM + CAS + ext) and to verify that once configured the whole system works.

Is there a “dev” license available for CAS server that can be used to install it on a development environment and where it would be possible to check if an integration works as expected ?

Same question for the BATM part, is there a dev/simulation environment available to verify things from the end-user perspective ? 
The CAS configuration and setup guide describes that it is possible to add a virtual terminal, is it the recommended way to test it ?

Or, is it just not possible unless a terminal is bought ?

Many thanks for your answers !

**Comment by rudygodoy** [comment]
@jpbriquet virtual terminal is intended to be used through the API for operations of a regular BTM.

**Comment by generalbytes** [comment]
Virtual terminals will not help you.
You have to have a hw machine to invoke purchases on server. 
Usually you code extension for somebody who has the machine and the server license so it shouldn't be an issue.
For 99% of the use cases using current "The test tool" is more than enough.
