### ISSUE TITLE
RateSource working with server_extensions_test but not with CAS

### ISSUE THREAD

**Issue by int3hh** [GENERALBYTESCOM/batm_public#153]
```
log.info(String.valueOf(rate).concat(preferedFiatCurrency));
IRateSource p = new FixPriceRateSource(rate, preferedFiatCurrency);
log.error(String.valueOf(p.getExchangeRateLast("RONC", "RON")));
```
 
**server_extensions_test output**
> [main] INFO batm.master.ronc - 1000RON
> [main] ERROR batm.master.ronc - 1000

**CAS output**
> [main] INFO batm.master.ronc - 1000RON
> [main] ERROR batm.master.ronc - null

Any hint ?

**Comment by int3hh** [comment]
RONC is the crypto
RON is fiat

**Comment by int3hh** [comment]
Fixed by implementing my own IRateSource still why this behaviour ?

**Comment by generalbytes** [comment]
No idea. Might be relating to classloader. Perhaps you had 2 jars in path containing 2 versions of  FixPriceRateSource.
