### ISSUE TITLE
implement sell on cryptocurrency

### ISSUE THREAD

**Issue by cryptodiggers** [GENERALBYTESCOM/batm_public#158]
Hi, 
I would like to know which classes do I need to implement to allow a sell on the atm for a cryptocurrency. I assume that i need to implement the part IBlockchainWatcher but what else need to be implemented ? In the first attempt I want to implement sell only to HotWallet via rpcclient. 

Thank you,
Martin

**Comment by ergofobe** [comment]
I'd also like to know how to do this, but more particularly how this would be implemented for currencies that don't use unique addresses to identify transactions but rather something like a tag (XRP) or attachment (WAVES) or worse still something like ETH that has no such mechanism in the protocol.

Presumably you'd also have to somehow modify printer_sell_crypto_ticket_template to include additional text related to the tag/attachment and have that info included in the QR code as well.

**Comment by rpanak-generalbytes** [comment]
Here is example implementation for BitcoinCash.
[b4c9839](https://github.com/GENERALBYTESCOM/batm_public/commit/b4c98398a7efdbb18da93ed6c5ab53c1a5744e0c)
