### ISSUE TITLE
Request : IRateSource CoinMarketCap JSON API

### ISSUE THREAD

**Issue by gamers-coin** [GENERALBYTESCOM/batm_public#16]
Hi batm Team

Can you maybe write a CoinMarketCap JSON API IRateSource Template ???

CoinMarketCap JSON API :+1: 
http://coinmarketcap-nexuist.rhcloud.com/
http://coinmarketcap-nexuist.rhcloud.com/api/btc
http://coinmarketcap-nexuist.rhcloud.com/api/game
http://coinmarketcap-nexuist.rhcloud.com/api/doge
http://coinmarketcap-nexuist.rhcloud.com/api/ltc

680 Supported Coins :
https://coinmarketcap.com/currencies/views/all/

Kind regards

**Comment by generalbytes** [comment]
There is no demand for that.
