### ISSUE TITLE
Need Information on adding new coin

### ISSUE THREAD

**Issue by naveen7252** [GENERALBYTESCOM/batm_public#162]
Hi,
We want to add our coin NULS to BATM. I have gone through the code to understand the process.
can you please clarify me on this?

1. Rate Source: We would be using binance or coinmarketcap as rate source. We are good here.
2. Wallet: We want to add Binance as source for buying the coins. How will this be done? BATM will have it's own binance account to buy the NULS coins? And, we as part of Extension development, add the implementation to buy from Binance?

Please help us on the point:2

Thanks

**Comment by chrisrico** [comment]
You'll want to implement [IExchangeAdvanced](https://github.com/GENERALBYTESCOM/batm_public/blob/master/server_extensions_api/src/main/java/com/generalbytes/batm/server/extensions/IExchangeAdvanced.java). Probably the easiest way to do that is to subclass [XChangeExchange](https://github.com/GENERALBYTESCOM/batm_public/blob/master/server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/bitcoin/exchanges/XChangeExchange.java) and plug in the [xchange-binance module](https://github.com/knowm/XChange/tree/develop/xchange-binance). You can look at the [ItBitExchange](https://github.com/GENERALBYTESCOM/batm_public/blob/master/server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/bitcoin/exchanges/itbit/ItBitExchange.java) implementation to see how that is done.

**Comment by naveen7252** [comment]
Hi, Thanks for the information.
I see Lisk uses Binance as a wallet, so I can go with the same implementation for our coin NULS right. 
Do I still need to implement exchange functionality ? I don't see it was done for Lisk coin.

Thanks

**Comment by rpanak-generalbytes** [comment]
The minimum you'll need is IWallet and IRateSource implementation. Implementing IExchange or IExchangeAdvanced add greater flexibility. Without it you have to refill your hot wallet manually to make sure enough coins are available.

**Comment by naveen7252** [comment]
thanks for the information
