### ISSUE TITLE
Can not implement two-way for our coin

### ISSUE THREAD

**Issue by phinamcn03** [GENERALBYTESCOM/batm_public#164]
I was try two-way sample for BitcoinCash and Sumcoin but my coin still one way. 
Steps i do:
- Add my coin into com.generalbytes.batm.server.extensions.Currencies
- Copy BitcoinCash extension folder to mycoin, rename and change all reference from BitcoinCash to MyCoin
- Add extension tag in to batm-extensions.xml

have I forgotten any step?

**Comment by rpanak-generalbytes** [comment]
The code needs to be specific to your coin. I don't know whether just renaming the references to BCH is enough. Also, you don't mention what's not working, so it's hard to help you.

**Comment by phinamcn03** [comment]
Thanks rpanak. That problem was fixed.
I missing rename one place.
