### ISSUE TITLE
Sell Implementation on our Coin

### ISSUE THREAD

**Issue by DeanJayEm** [GENERALBYTESCOM/batm_public#174]
Hi, I already did all the process and changes but i got this error
![sellerror](https://user-images.githubusercontent.com/29330611/53388743-52169e80-39c7-11e9-96c0-10dad3559af4.png)

**Comment by DeanJayEm** [comment]
@rpanak-generalbytes please help

**Comment by rpanak-generalbytes** [comment]
It seems maybe your code returns null somewhere instead of a proper object. The method on the top of the stacktrace is part of our public repository. You can add debug prints of all the parameter values to the method and look at what's actually null.

**Comment by DeanJayEm** [comment]
Hi, here is my repository. will you please check it out. Cheers! Thank you.
it is in "bitpal" folder/package
https://bitbucket.org/JayEm13/batm_public_bpi/src/master/

**Comment by DeanJayEm** [comment]
Our coin uses REST API calls not RPC calls. Is there anyway to extend the sell using REST API calls?

**Comment by rpanak-generalbytes** [comment]
@DeanJayEm 
you have all the instructions to help yourself. We don't offer free development services. If you are unable to proceed on your own, we can provide a developer that can take a look. However, this service is billed according to the time spent by the developer.

As for the RPC vs REST:
- I imagine you are referring to the RPCClient. Despite the name, AFAIK it actually uses REST as well to communicate with a bitcoind compatible wallet.

- You don't have to extend AbstractRPCPaymentSupport (with abstract methods passing RPC client). This is just a shortcut to implement IPaymentSupport for currencies that use forks of bitcoind (or something compatible).

- you can use whatever you like as long as you implement the required interfaces. If you don't want to use the RPCClient, skip the abstract skeleton classes and implement the interfaces directly (there should be no abstract methods using RPCClient in the interfaces).

**Comment by DeanJayEm** [comment]
Hi, I got it working , thanks anyway.

**Comment by rpanak-generalbytes** [comment]
Great! Closing the issue.
