### ISSUE TITLE
Redeem Ticket not working for Sumcoin

### ISSUE THREAD

**Issue by phinamcn03** [GENERALBYTESCOM/batm_public#177]
Hi
I Setup Sumcoin to our BATM but redeem ticket not working. (I haven't try BCH yet).
In cryptos setting: add sumcoin, setup hot wallet (run test all => All OK)
But when i sell i get stuck at redeem ticket. BATM does not recognize QR codes of sumcoin

**Comment by generalbytes** [comment]
Most likely you are running old version of terminal or server.

**Comment by phinamcn03** [comment]
Server version: 20190217
Terminal version: 20190128
