### ISSUE TITLE
Use cash dispenser not the cash acceptor to withdraw cash

### ISSUE THREAD

**Issue by DeanJayEm** [GENERALBYTESCOM/batm_public#179]
Hi I would like to ask how to use the cash dispenser to withdraw cash ? thanks!
![c2b4f7a7-d9a5-411b-9676-e6b1d917b1cd](https://user-images.githubusercontent.com/29330611/53778440-b8f00680-3f37-11e9-9821-80ba864e50a9.jpg)

**Comment by DeanJayEm** [comment]
@rpanak-generalbytes

**Comment by rpanak-generalbytes** [comment]
Contact our tech support via the contact form on our web page.
