### ISSUE TITLE
BATM3 BUY and SELL Process Flow for BPI coin

### ISSUE THREAD

**Issue by DeanJayEm** [GENERALBYTESCOM/batm_public#181]
Hi General bytes @rpanak-generalbytes , we would like your help to change the process flow of the BATMTHREE? 
We basically want to change the process of buying and selling on the ATM machines.
We created a sample website of the atm's interface on how we want the process to be. https://testbox.bitpalint.com/atm/

Here are the changes we would like your help with. 

We placed the "Buy", "Sell", and "Check wallet balance" on the first page and moved the choosing of assets to the second page. We basically swap the first page and second page. The reason we made this change is because we want the user to pick the action they wanted first. And we're also thinking this way we can limit the assets that will support/show in "Buying" and "Selling".

We also want to change the end part of "Sell". Right now in sell feature you have to enter the amount you want to withdraw, then the ATM will print a QR code for the user, then the user will send funds to that QR code then later redeem the ticket. We want to change this process and remove the redeem ticket. Instead here's the process we want. The user enters the amount they want then instead of printing a QR code we want to show the QR code on the screen, and then the user will scan and send funds to that QR code then automatically dispense the cash as soon as the transaction is completed.

We made this change because our crypto currency only takes a few seconds to send funds so there's no point of letting the user go back to the machine and redeem the ticket after they send funds on it. This will only work with a BitPal wallet. Because we built our system using the Bitshares technology, our system is extremely fast. 

Also look at our YouTube videos using BitPal Int so you can see our progress.
https://www.youtube.com/watch?v=sc1dTxfnTZU&list=PLorYonMhPpiFfQ5kK_5dOAcpYQgbURdr9

**Comment by rpanak-generalbytes** [comment]
Hi. Different currencies can support different actions, so the first screen is the coin choice.
As for changing the SELL flow and merging it with WITHDRAW, this is a relatively big change. The ticket is printed on purpose so that in case of unexpected failure the customer has at least some physical evidence about the transaction. Currently, we have no plans to change the UI flow the way you described.

**Comment by wvabitpal** [comment]
Hi @rpanak-generalbytes  Is there a way for us to do the changes we described?

**Comment by rpanak-generalbytes** [comment]
Unfortunately no. This is not part of the public GitHub repo. 
If you are interested, we offer custom development services. Please contact our support through the webpage form if you are interested in getting a quote.
