### ISSUE TITLE
Dynamic gas limit calculation broken

### ISSUE THREAD

**Issue by gurvy522** [GENERALBYTESCOM/batm_public#187]
Right now we're experiencing two issue with GB's native ERC20 implementation, that are both somewhat related, so I'll create a single issue for this. 

Currently, the logic is dynamically calculating how much gas we need for a transaction, and then to play it safe, multiply it by 1.1 to create 10% extra headroom in case it costs more. In testing, we've noticed multiple ERC20 transactions running out of gas, as the dynamic calculation, even with the 10% extra limit, is still too low. (IE gas limit calculated at around 40,000 with 1.1x, yet transaction probably costs closer to 50,000-60,000 gas)

The other issue we were having is that for some reason the dynamic gas calculation wasn't even working with certain contracts, and would return null. I'm not sure if this is due specifically to the way that certain ERC20 contracts are written, even though they all should follow the same standard. We were trying to dig more into why this was happening by adding additional logging to the extension, to no avail.

So, as a fix, we hardcoded the gas limit in our private repo (for the ERC20Wallet). The concept of the gas limit primarily exists to prevent spending gas on excess code execution, like for instance if you're executing a buggy contract. Ideally, all ERC20 transfer functions should cost around the same amount of gas, and this really shouldn't change much as long as the tokens are following the ERC20 standard. 

It makes a lot of sense to dynamically calculate the gas price, as that can fluctuate depending on how loaded up the ETH network is at any given time. But for the gas limit, it should most likely either be hardcoded or set as a configurable parameter through the CAS.

**Comment by generalbytes** [comment]
I agree gas limit calculation is always an alchemy and parameter is needed to make service reliable.
https://github.com/GENERALBYTESCOM/batm_public/commit/fe1648a453552b6ba5539423c8d4cbfc2038c07f
It will be released in upcoming release next week.
