### ISSUE TITLE
Unable to start master process after adding custom coin

### ISSUE THREAD

**Issue by int3hh** [GENERALBYTESCOM/batm_public#188]
Server version : 20190319

Hello,

After adding our coin the master process won't start it exits with the following error:

> Exception in thread "»/Master-start/1" java.lang.NoSuchFieldError: RONC
> 	at com.generalbytes.batm.server.extensions.extra.ronc.RONCExtension.getSupportedCryptoCurrencies(RONCExtension.java:34)
> 	at com.generalbytes.batm.server.extensions.e.b(GB:364)
> 	at com.generalbytes.batm.server.services.e.a(GB:2097)
> 	at com.generalbytes.batm.server.ServerMain.main(GB:7)

The function where the error is reported is a copy paste from other extensions:

`  @Override
    public Set<String> getSupportedCryptoCurrencies() {

        Set<String> result = new HashSet<String>();
        result.add(CryptoCurrency.RONC.getCode());
        return result;

    }
`

Obviously RONC is defined in CryptoCurrency like this :   RONC("RonCoin"),

Also if I replace RONC with SUM for example inside that function the master process starts.

How can we fix ?

**Comment by generalbytes** [comment]
It seems that you were modifying https://github.com/GENERALBYTESCOM/batm_public/blob/master/currencies/src/main/java/com/generalbytes/batm/common/currencies/CryptoCurrency.java
by adding RONC("RonCoin"), but you did't copy new currencies-1.0-SNAPSHOT.jar to /batm/app/master/lib

**Comment by int3hh** [comment]
Please include it in the readme. Thank you for your prompt answer.

**Comment by brandonbryant12** [comment]
> It seems that you were modifying https://github.com/GENERALBYTESCOM/batm_public/blob/master/currencies/src/main/java/com/generalbytes/batm/common/currencies/CryptoCurrency.java
> by adding RONC("RonCoin"), but you did't copy new currencies-1.0-SNAPSHOT.jar to /batm/app/master/lib

Where is `currencies-1.0-SNAPSHOT.jar` built to?

I build the project with `./gradlew build` 
and then search with `grep -re currencies-1.0-SNAPSHOT.jar .` and find nothing
