### ISSUE TITLE
test sell rate exception

### ISSUE THREAD

**Issue by int3hh** [GENERALBYTESCOM/batm_public#189]
All tests run succesefully I can see rate buy and rate sell correct after runing tests but when I try to deploy I receive this:

> 2019-03-21 11:32:19.813 [BUS-2000] ERROR batm.master.IPC - testSellRateSource (1)
> java.lang.NullPointerException: null
> 	at com.generalbytes.batm.server.extensions.extra.ethereum.EthereumExtension.createRateSource(EthereumExtension.java:88)
> 	at com.generalbytes.batm.server.extensions.e.b(GB:134)
> 	at com.generalbytes.batm.server.services.d.b(GB:219)
> 	at com.generalbytes.batm.server.services.d.testTerminalConfiguration(GB:161)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at com.caucho.hessian.server.HessianSkeleton.invoke(HessianSkeleton.java:192)
> 	at com.caucho.hessian.server.HessianSkeleton.invoke(HessianSkeleton.java:110)
> 	at com.generalbytes.bus.impl.BusService.handle(BusService.java:72)
> 	at com.generalbytes.bus.impl.BusService.access$100(BusService.java:17)
> 	at com.generalbytes.bus.impl.BusService$1.run(BusService.java:102)
> 	at java.lang.Thread.run(Thread.java:748)
> 

What is the problem ? Thank you

**Comment by int3hh** [comment]
I have a fixed ratesource defined for the cryptocurrency the problem is that for sell CAS sends sourceLogin = null. why ?

**Comment by pvyhnal-generalbytes** [comment]
Are you using modified version of EthereumExtension.java? Can you share it?
Can you check your configuration parameters in CAS for correct formatting or paste it here (with sensitive data like api keys masked)?

**Comment by int3hh** [comment]
No, the problem is for my extension when you press SELL rate test, the CAS sends SourceLogin parameter with null value and that affects the EthereumExtension too because it lacks a null check

**Comment by int3hh** [comment]
I have shared with you our repo, please correct the issues so that sell rate actually works and a payment request is generated properly.

**Comment by pvyhnal-generalbytes** [comment]
Sell is not yet supported for Ethereum. It has to be implemented in CAS first before it can be used by extensions.

**Comment by int3hh** [comment]
Our extension has nothing to do with ETHEREUM!!! IT IS A CUSTOM EXTENSION that implements the newly added IPaymentSupport for selling coins. Did you bother to check the repository I shared with you ? You understand that I talked to your team members and this is a paid support ?

**Comment by rpanak-generalbytes** [comment]
@int3hh AFAIK you haven't yet paid nor agreed to pay for support, so this is not a case of paid support. What makes you claim that?

**Comment by int3hh** [comment]
@rpanak-generalbytes I agreed with your NASA rate / h of 200 USD, and your support said has assigned a developer to the issue. You are trying to teach me a lesson or you want to help your customer ?

**Comment by rpanak-generalbytes** [comment]
@int3hh Nope, you haven't agreed. Our support has assigned a developer to **evaluate** your issue, which we were doing for **free**. Nobody is trying to teach you a lesson, but you could mind your manners. As you might be aware, you're not the only customer we're trying to help.

The problem you're facing should be fixed in #192. It is not connected with your extension code. Enjoy the free fix, you can use the saved funds for some NASA services.

**Comment by int3hh** [comment]
@rpanak-generalbytes looks like your teaching me manners, is ok most people tend to hide their technical incompetence by blaming their talker: is not using proper language, doesn't explain too good or is too stupid to understand, etc. I am aware that you have other customers but after talking 2 days with your support, agreeing to pay whatever huge costs to solve my problem although I am quite sure the mistake is on your side, you give me answers that make no sense. So could you understand my frustration and tone now ? I hope you do. 

I don't know why after selling atms worth approx 18 mil euros, you lack proper support and skilled people and I must praise when I receive a answer that has no sense so please excuse my manners.

Btw your so called solution won't work, because obviously I have put that null check in EthereumExtension I don't receive any exception but still null is passed to my ratesource provider and still doesn't work.

I won't bother you anymore with any issue so Kudos for one satisfied customer!

**Comment by generalbytes** [comment]
Just finished testing. RONC rate source works fine without any issue. Used extra extensions built from here:
https://github.com/int3hh/batm2/
