### ISSUE TITLE
ATM code modification

### ISSUE THREAD

**Issue by DappWay** [GENERALBYTESCOM/batm_public#195]
Hi all,

Is there somewhere in GitHub ATM side code?
Can we modify and update it?

Thanks,

**Comment by generalbytes** [comment]
I'm sorry. Client part of the ATM is not open-source.
You can add coins by adding them on server. 
What is the change you are trying to achieve?

**Comment by DappWay** [comment]
I want to implement sell functionality. It there a way for it?

**Comment by generalbytes** [comment]
Sell functionality you can implement by extension on server side.
Take a look at Bicoincash how this has been achieved. You need to implement CryptoCurrencyDefinition including IPaymentSupport.
More info here:
https://github.com/GENERALBYTESCOM/batm_public/blob/77497351480103eee83235fe8b28bcb8c998469f/server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/bitcoincash/BitcoinCashExtension.java#L79
