### ISSUE TITLE
Add XRP

### ISSUE THREAD

**Issue by dappway** [GENERALBYTESCOM/batm_public#197]
Hi,

There is a problem by adding XRP coin as it requires address and addressTag.
On ATM side QR code is generated just by address. 

Can we add addressTag to QR code generation?

**Comment by DappWay** [comment]
Hi all,

Any update on this question?

**Comment by generalbytes** [comment]
Hi,
Yes we are aware of this limitation. XRP is on our roadmap, but we don't plan to modify UI at this moment to allow entering XRP specific thing called addressTag/destinationTag.

**Comment by generalbytes** [comment]
XRP support was added in
