### ISSUE TITLE
Integration of server_extensions_extra TransactionExtension.java into CAS does not populate

### ISSUE THREAD

**Issue by jaketarnow** [GENERALBYTESCOM/batm_public#207]
I have added in some test code locally to the `TransactionExtension.java` in the `server_extensions_extra` examples sub directory. When compiling and un-commenting the TransactionExtension in the `batm-extensions.xm`l and placing in the `/batm/app/master/extensions/` I notice that the master log shows that it picked up the `batm-extensions.xml` but my test code never gets called when a transaction occurs in the `isTransactionApproved` method. Is this because the method overrides ITransactionListener.java which is in the server_extensions_api which was not compiled and moved into `/batm/app/master/extensions/`? Your help is much appreciated.

**Comment by generalbytes** [comment]
What version of server are you using?

**Comment by jaketarnow** [comment]
@generalbytes the version of the server is: 20190403

**Comment by generalbytes** [comment]
1. Please unzip your extension jar and check if it really contains .xml file with uncommented TransactionExtension.
2. If possible wite here link to your extension.jar and we will inspect it.
3. Is onTransactionCreated called on your TransactionExtension?

**Comment by jaketarnow** [comment]
@generalbytes 
1. Unzipped .xml file has `com.generalbytes.batm.server.extensions.extra.examples.TransactionExtension` uncommented
3. Yes, it is called in the TransactionExtension:
@Override
    public boolean isTransactionApproved(ITransactionRequest transactionRequest) {

**Comment by generalbytes** [comment]
Please answer again #2 and #3.

**Comment by jaketarnow** [comment]
@generalbytes I answered 1 and 3 above. I have removed all intellectual property from the jar file and added in some temp code similar to what I am working on. The jar file is linked here: https://github.com/jaketarnow/CryptoBlockReview/blob/master/Crypto/batm_server_extensions_extra.jar. Hope to hear back soon

**Comment by jaketarnow** [comment]
@generalbytes any update on this??

**Comment by jaketarnow** [comment]
@generalbytes Checking in to see if you've had a chance to re-visit this. Thanks!

**Comment by generalbytes** [comment]
Yes, We did and isTransactionApproved is called on extension
