### ISSUE TITLE
Suggestion: Implementing Bip38

### ISSUE THREAD

**Issue by PeterAlfonsLoch** [GENERALBYTESCOM/batm_public#212]
As I understand the nfc cards save the private key as plaintext? How about allowing bip38? at least for reading? Or creating an open source payment standard?

**Comment by generalbytes** [comment]
We decided not to use password encrypted private keys (BIP38) because that typical users that don't have mobile wallet and therefore use NFC cards are unable to remember passwords.
Risk of forgetting password is higher than having 3rd party scanning NFC private key from card in your pocket.
