### ISSUE TITLE
Bech32 address validator

### ISSUE THREAD

**Issue by cryptodiggers** [GENERALBYTESCOM/batm_public#226]
Hi, 

I am trying to build a Bech32 address validator for the Litecoin. I have the validator class, but when I scan the Bech32 address i do not see in the log that the validator was initiated.

I should see after the scan of the bech32 address a log entry: "Checking address <bech32 address>, but it is not present. I have the latest batm and also latest firmware on automate.

This is the part of the code:
`@Override
    public boolean isAddressValid(String address) {
        log.debug("Checking address ["+address+"] ");
        if (address.startsWith("L") || address.startsWith("3") || address.startsWith("M")) {
            try {
                Base58.decodeToBigInteger(address);
                Base58.decodeChecked(address);
            } catch (AddressFormatException e) {
                log.debug("Address ["+address+"] was not recognized.", e);
                return false;
            }
            return true;
        }else{
            try{
                Bech32cdp.Bech32Data addr;
                addr=Bech32cdp.decode(address);
                if(addr.getHrp().contentEquals("ltc")){
                    log.debug("Address ["+address+"] was recognized.");
                    return true;
                }
                else{
                    log.debug("Address ["+address+"] was not recognized.");
                    return false;
                }
            }
            catch(AddressFormatExceptionCdp e){
                log.debug("Address ["+address+"] was not recognized.", e);
                return false;
            }
        }
    }`

I have also extended the test.java to test if the function is working and the validator function is working.

I have also added the validator to the LitecoinExtension.java:
`@Override
    public ICryptoAddressValidator createAddressValidator(String cryptoCurrency) {
        if (CryptoCurrency.LTC.getCode().equalsIgnoreCase(cryptoCurrency)) {
            return new LitecoinAddressValidator();
        }
        return null;
    }`

I do not see any exception in the log that any class or lib is missing.

Am I missing some setting somewhere else ?

One more info:
The screen show "Please use supported LTC wallet"

P.S. the Litecoin build in Kraken extension also does not support the bech32 address.

BR,
Martin

**Comment by generalbytes** [comment]
You are modifying address validator that is executed on server side.
Before performing validation on server side is also performed validation on client side (using bitrafael library)

Bech32 support for BTC and LTC was added in terminal version 20190613. It should be ok now.
