### ISSUE TITLE
How to add ADA coin (cardano)

### ISSUE THREAD

**Issue by saravanans88** [GENERALBYTESCOM/batm_public#239]
I am trying to add ADA coin . It is POS fork.  In batm_public , all commands are derived from BitcoinJSONRPCClient like following,

getClient(rpcURL).**getAddressesByAccount**(accountName);

getAddressesByAccount is not available for ADA coin.  Can i change the code for my requirement without using **BitcoinJSONRPC**

**Comment by generalbytes** [comment]
I don't think we use getAddressByAccount.
Take a look here:  
https://github.com/GENERALBYTESCOM/batm_public/blob/master/server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/bitcoin/wallets/bitcoind/BATMBitcoindRPCWallet.java

**Comment by saravanans88** [comment]
ADA coin does not support getnewaddress,getAccount,getAccountAddress,getAddressesByAccount commands.

 API call for ADA coin is different like below,

curl -X POST  https://127.0.0.1:8090/api/v1/addresses  \
  -H "Accept: application/json; charset=utf-8" \
  -H "Content-Type: application/json; charset=utf-8" \
  --cert ./state-wallet-testnet/tls/client/client.pem \
  --cacert ./state-wallet-testnet/tls/client/ca.crt \
  -d '{
    "accountIndex": 2147483680,
    "walletId": "2cWKMJemoBajqLDmj2BmQMGdMrFPartY1oFFrJMRmn35KQbEqarXYbCQNLuyZTgrJucQ9"
}'.  

Can i implement my own set of code to create address without using BitcoinJSONRPCClient.java
