### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by letreset** [GENERALBYTESCOM/batm_public#246]
We are getting this error while compiling on ubuntu 18.04 with oracle java 12. How can we solve it?

> > Task :server_extensions_extra:compileJava
> /root/batm_public/server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/watchlists/eu/tags/NameAliasType.java:11: error: package javax.xml.bind.annotation does not exist
> import javax.xml.bind.annotation.XmlAccessType;
>                                 ^
> /root/batm_public/server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/watchlists/eu/tags/NameAliasType.java:12: error: package javax.xml.bind.annotation does not exist
> import javax.xml.bind.annotation.XmlAccessorType;
>                                 ^
> /root/batm_public/server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/watchlists/eu/tags/NameAliasType.java:13: error: package javax.xml.bind.annotation does not exist
> import javax.xml.bind.annotation.XmlAttribute;
>                                 ^
> /root/batm_public/server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/watchlists/eu/tags/NameAliasType.java:14: error: package javax.xml.bind.annotation does not exist
> import javax.xml.bind.annotation.XmlType;
>                                 ^
> /root/batm_public/server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/watchlists/eu/tags/SanctionableType.java:11: error: package javax.xml.bind.annotation does not exist
> import javax.xml.bind.annotation.XmlAccessType;
>                                 ^
> /root/batm_public/server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/watchlists/eu/tags/SanctionableType.java:12: error: package javax.xml.bind.annotation does not exist
> import javax.xml.bind.annotation.XmlAccessorType;
>                                 ^
> /root/batm_public/server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/watchlists/eu/tags/SanctionableType.java:13: error: package javax.xml.bind.annotation does not exist
> import javax.xml.bind.annotation.XmlAttribute;
>                                 ^
> /root/batm_public/server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/watchlists/eu/tags/SanctionableType.java:14: error: package javax.xml.bind.annotation does not exist
> import javax.xml.bind.annotation.XmlElement;
>                                 ^
> /root/batm_public/server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/watchlists/eu/tags/SanctionableType.java:15: error: package javax.xml.bind.annotation does not exist
> import javax.xml.bind.annotation.XmlSeeAlso;
>                                 ^
> /root/batm_public/server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/watchlists/eu/tags/SanctionableType.java:16: error: package javax.xml.bind.annotation does not exist
> import javax.xml.bind.annotation.XmlType;
>                                 ^
> /root/batm_public/server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/watchlists/eu/tags/OperableType.java:13: error: package javax.xml.bind.annotation does not exist
> import javax.xml.bind.annotation.XmlAccessType;
>                                 ^
> /root/batm_public/server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/watchlists/eu/tags/OperableType.java:14: error: package javax.xml.bind.annotation does not exist
> import javax.xml.bind.annotation.XmlAccessorType;
>                                 ^
> /root/batm_public/server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/watchlists/eu/tags/OperableType.java:15: error: package javax.xml.bind.annotation does not exist
> import javax.xml.bind.annotation.XmlAttribute;
>                                 ^
> /root/batm_public/server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/watchlists/eu/tags/OperableType.java:16: error: package javax.xml.bind.annotation does not exist
> import javax.xml.bind.annotation.XmlSeeAlso;
>                                 ^
> /root/batm_public/server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/watchlists/eu/tags/OperableType.java:17: error: package javax.xml.bind.annotation does not exist
> import javax.xml.bind.annotation.XmlType;
>                                 ^
> /root/batm_public/server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/watchlists/eu/tags/OperableType.java:44: error: cannot find symbol
> @XmlAccessorType(XmlAccessType.FIELD)
>  ^
>   symbol: class XmlAccessorType
> /root/batm_public/server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/watchlists/eu/tags/OperableType.java:45: error: cannot find symbol
> @XmlType(name = "OperableType", propOrder = {
>  ^
>   symbol: class XmlType
> /root/batm_public/server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/watchlists/eu/tags/OperableType.java:49: error: cannot find symbol
> @XmlSeeAlso({
>  ^
>   symbol: class XmlSeeAlso
> /root/batm_public/server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/watchlists/eu/tags/SanctionableType.java:41: error: cannot find symbol
> @XmlAccessorType(XmlAccessType.FIELD)
>  ^
>   symbol: class XmlAccessorType
> /root/batm_public/server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/watchlists/eu/tags/SanctionableType.java:42: error: cannot find symbol
> @XmlType(name = "SanctionableType", propOrder = {
>  ^
>   symbol: class XmlType
> /root/batm_public/server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/watchlists/eu/tags/SanctionableType.java:45: error: cannot find symbol
> @XmlSeeAlso({
>  ^
>   symbol: class XmlSeeAlso
> /root/batm_public/server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/watchlists/eu/tags/NameAliasType.java:46: error: cannot find symbol
> @XmlAccessorType(XmlAccessType.FIELD)
>  ^
>   symbol: class XmlAccessorType
> /root/batm_public/server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/watchlists/eu/tags/NameAliasType.java:47: error: cannot find symbol
> @XmlType(name = "NameAliasType")
>  ^
>   symbol: class XmlType
> /root/batm_public/server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/watchlists/eu/tags/ExportType.java:13: error: package javax.xml.bind.annotation does not exist
> import javax.xml.bind.annotation.XmlAccessType;
>                                 ^
> /root/batm_public/server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/watchlists/eu/tags/ExportType.java:14: error: package javax.xml.bind.annotation does not exist
> import javax.xml.bind.annotation.XmlAccessorType;
>                                 ^
> /root/batm_public/server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/watchlists/eu/tags/ExportType.java:15: error: package javax.xml.bind.annotation does not exist
> import javax.xml.bind.annotation.XmlAttribute;
>                                 ^
> /root/batm_public/server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/watchlists/eu/tags/ExportType.java:16: error: package javax.xml.bind.annotation does not exist
> import javax.xml.bind.annotation.XmlRootElement;
>                                 ^
> /root/batm_public/server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/watchlists/eu/tags/ExportType.java:17: error: package javax.xml.bind.annotation does not exist
> import javax.xml.bind.annotation.XmlType;
>                                 ^
> /root/batm_public/server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/watchlists/eu/tags/ExportType.java:42: error: cannot find symbol
> @XmlRootElement(name = "export", namespace = "http://eu.europa.ec/fpi/fsd/export")
>  ^
>   symbol: class XmlRootElement
> /root/batm_public/server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/watchlists/eu/tags/ExportType.java:43: error: cannot find symbol
> @XmlAccessorType(XmlAccessType.FIELD)
>  ^
>   symbol: class XmlAccessorType
> /root/batm_public/server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/watchlists/eu/tags/ExportType.java:44: error: cannot find symbol
> @XmlType(name = "ExportType", propOrder = {
>  ^
>   symbol: class XmlType
> /root/batm_public/server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/watchlists/eu/tags/SanctionEntityType.java:13: error: package javax.xml.bind.annotation does not exist
> import javax.xml.bind.annotation.XmlAccessType;
>                                 ^
> /root/batm_public/server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/watchlists/eu/tags/SanctionEntityType.java:14: error: package javax.xml.bind.annotation does not exist
> import javax.xml.bind.annotation.XmlAccessorType;
>                                 ^
> /root/batm_public/server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/watchlists/eu/tags/SanctionEntityType.java:15: error: package javax.xml.bind.annotation does not exist
> import javax.xml.bind.annotation.XmlAttribute;
>                                 ^
> /root/batm_public/server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/watchlists/eu/tags/SanctionEntityType.java:16: error: package javax.xml.bind.annotation does not exist
> import javax.xml.bind.annotation.XmlElement;
>                                 ^
> /root/batm_public/server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/watchlists/eu/tags/SanctionEntityType.java:17: error: package javax.xml.bind.annotation does not exist
> import javax.xml.bind.annotation.XmlType;
>                                 ^
> /root/batm_public/server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/watchlists/eu/tags/SanctionEntityType.java:55: error: cannot find symbol
> @XmlAccessorType(XmlAccessType.FIELD)
>  ^
>   symbol: class XmlAccessorType
> /root/batm_public/server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/watchlists/eu/tags/SanctionEntityType.java:56: error: cannot find symbol
> @XmlType(name = "SanctionEntityType", propOrder = {
>  ^
>   symbol: class XmlType
> /root/batm_public/server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/watchlists/eu/tags/RegulationType.java:13: error: package javax.xml.bind.annotation does not exist
> import javax.xml.bind.annotation.XmlAccessType;
>                                 ^
> /root/batm_public/server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/watchlists/eu/tags/RegulationType.java:14: error: package javax.xml.bind.annotation does not exist
> import javax.xml.bind.annotation.XmlAccessorType;
>                                 ^
> /root/batm_public/server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/watchlists/eu/tags/RegulationType.java:15: error: package javax.xml.bind.annotation does not exist
> import javax.xml.bind.annotation.XmlAttribute;
>                                 ^
> /root/batm_public/server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/watchlists/eu/tags/RegulationType.java:16: error: package javax.xml.bind.annotation does not exist
> import javax.xml.bind.annotation.XmlType;
>                                 ^
> /root/batm_public/server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/watchlists/eu/tags/RegulationType.java:48: error: cannot find symbol
> @XmlAccessorType(XmlAccessType.FIELD)
>  ^
>   symbol: class XmlAccessorType
> /root/batm_public/server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/watchlists/eu/tags/RegulationType.java:49: error: cannot find symbol
> @XmlType(name = "RegulationType", propOrder = {
>  ^
>   symbol: class XmlType
> /root/batm_public/server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/watchlists/eu/tags/SubjectTypeType.java:11: error: package javax.xml.bind.annotation does not exist
> import javax.xml.bind.annotation.XmlAccessType;
>                                 ^
> /root/batm_public/server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/watchlists/eu/tags/SubjectTypeType.java:12: error: package javax.xml.bind.annotation does not exist
> import javax.xml.bind.annotation.XmlAccessorType;
>                                 ^
> /root/batm_public/server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/watchlists/eu/tags/SubjectTypeType.java:13: error: package javax.xml.bind.annotation does not exist
> import javax.xml.bind.annotation.XmlAttribute;
>                                 ^
> /root/batm_public/server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/watchlists/eu/tags/SubjectTypeType.java:14: error: package javax.xml.bind.annotation does not exist
> import javax.xml.bind.annotation.XmlType;
>                                 ^
> /root/batm_public/server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/watchlists/eu/tags/SubjectTypeType.java:37: error: cannot find symbol
> @XmlAccessorType(XmlAccessType.FIELD)
>  ^
>   symbol: class XmlAccessorType
> /root/batm_public/server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/watchlists/eu/tags/SubjectTypeType.java:38: error: cannot find symbol
> @XmlType(name = "SubjectTypeType")
>  ^
>   symbol: class XmlType
> /root/batm_public/server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/watchlists/eu/tags/CitizenshipType.java:11: error: package javax.xml.bind.annotation does not exist
> import javax.xml.bind.annotation.XmlAccessType;
>                                 ^
> /root/batm_public/server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/watchlists/eu/tags/CitizenshipType.java:12: error: package javax.xml.bind.annotation does not exist
> import javax.xml.bind.annotation.XmlAccessorType;
>                                 ^
> /root/batm_public/server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/watchlists/eu/tags/CitizenshipType.java:13: error: package javax.xml.bind.annotation does not exist
> import javax.xml.bind.annotation.XmlAttribute;
>                                 ^
> /root/batm_public/server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/watchlists/eu/tags/CitizenshipType.java:14: error: package javax.xml.bind.annotation does not exist
> import javax.xml.bind.annotation.XmlType;
>                                 ^
> /root/batm_public/server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/watchlists/eu/tags/CitizenshipType.java:40: error: cannot find symbol
> @XmlAccessorType(XmlAccessType.FIELD)
>  ^
>   symbol: class XmlAccessorType
> /root/batm_public/server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/watchlists/eu/tags/CitizenshipType.java:41: error: cannot find symbol
> @XmlType(name = "CitizenshipType")
>  ^
>   symbol: class XmlType
> /root/batm_public/server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/watchlists/eu/tags/BirthdateType.java:11: error: package javax.xml.bind.annotation does not exist
> import javax.xml.bind.annotation.XmlAccessType;
>                                 ^
> /root/batm_public/server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/watchlists/eu/tags/BirthdateType.java:12: error: package javax.xml.bind.annotation does not exist
> import javax.xml.bind.annotation.XmlAccessorType;
>                                 ^
> /root/batm_public/server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/watchlists/eu/tags/BirthdateType.java:13: error: package javax.xml.bind.annotation does not exist
> import javax.xml.bind.annotation.XmlAttribute;
>                                 ^
> /root/batm_public/server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/watchlists/eu/tags/BirthdateType.java:14: error: package javax.xml.bind.annotation does not exist
> import javax.xml.bind.annotation.XmlType;
>                                 ^
> /root/batm_public/server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/watchlists/eu/tags/BirthdateType.java:49: error: cannot find symbol
> @XmlAccessorType(XmlAccessType.FIELD)
>  ^
>   symbol: class XmlAccessorType
> /root/batm_public/server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/watchlists/eu/tags/BirthdateType.java:50: error: cannot find symbol
> @XmlType(name = "BirthdateType")
>  ^
>   symbol: class XmlType
> /root/batm_public/server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/watchlists/eu/tags/AddressType.java:13: error: package javax.xml.bind.annotation does not exist
> import javax.xml.bind.annotation.XmlAccessType;
>                                 ^
> /root/batm_public/server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/watchlists/eu/tags/AddressType.java:14: error: package javax.xml.bind.annotation does not exist
> import javax.xml.bind.annotation.XmlAccessorType;
>                                 ^
> /root/batm_public/server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/watchlists/eu/tags/AddressType.java:15: error: package javax.xml.bind.annotation does not exist
> import javax.xml.bind.annotation.XmlAttribute;
>                                 ^
> /root/batm_public/server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/watchlists/eu/tags/AddressType.java:16: error: package javax.xml.bind.annotation does not exist
> import javax.xml.bind.annotation.XmlType;
>                                 ^
> /root/batm_public/server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/watchlists/eu/tags/AddressType.java:49: error: cannot find symbol
> @XmlAccessorType(XmlAccessType.FIELD)
>  ^
>   symbol: class XmlAccessorType
> /root/batm_public/server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/watchlists/eu/tags/AddressType.java:50: error: cannot find symbol
> @XmlType(name = "AddressType", propOrder = {
>  ^
>   symbol: class XmlType
> /root/batm_public/server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/watchlists/eu/tags/IdentificationType.java:11: error: package javax.xml.bind.annotation does not exist
> import javax.xml.bind.annotation.XmlAccessType;
>                                 ^
> /root/batm_public/server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/watchlists/eu/tags/IdentificationType.java:12: error: package javax.xml.bind.annotation does not exist
> import javax.xml.bind.annotation.XmlAccessorType;
>                                 ^
> /root/batm_public/server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/watchlists/eu/tags/IdentificationType.java:13: error: package javax.xml.bind.annotation does not exist
> import javax.xml.bind.annotation.XmlAttribute;
>                                 ^
> /root/batm_public/server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/watchlists/eu/tags/IdentificationType.java:14: error: package javax.xml.bind.annotation does not exist
> import javax.xml.bind.annotation.XmlType;
>                                 ^
> /root/batm_public/server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/watchlists/eu/tags/IdentificationType.java:51: error: cannot find symbol
> @XmlAccessorType(XmlAccessType.FIELD)
>  ^
>   symbol: class XmlAccessorType
> /root/batm_public/server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/watchlists/eu/tags/IdentificationType.java:52: error: cannot find symbol
> @XmlType(name = "IdentificationType")
>  ^
>   symbol: class XmlType
> /root/batm_public/server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/watchlists/eu/tags/ContactInfoType.java:11: error: package javax.xml.bind.annotation does not exist
> import javax.xml.bind.annotation.XmlAccessType;
>                                 ^
> /root/batm_public/server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/watchlists/eu/tags/ContactInfoType.java:12: error: package javax.xml.bind.annotation does not exist
> import javax.xml.bind.annotation.XmlAccessorType;
>                                 ^
> /root/batm_public/server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/watchlists/eu/tags/ContactInfoType.java:13: error: package javax.xml.bind.annotation does not exist
> import javax.xml.bind.annotation.XmlAttribute;
>                                 ^
> /root/batm_public/server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/watchlists/eu/tags/ContactInfoType.java:14: error: package javax.xml.bind.annotation does not exist
> import javax.xml.bind.annotation.XmlType;
>                                 ^
> /root/batm_public/server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/watchlists/eu/tags/ContactInfoType.java:37: error: cannot find symbol
> @XmlAccessorType(XmlAccessType.FIELD)
>  ^
>   symbol: class XmlAccessorType
> /root/batm_public/server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/watchlists/eu/tags/ContactInfoType.java:38: error: cannot find symbol
> @XmlType(name = "ContactInfoType")
>  ^
>   symbol: class XmlType
> /root/batm_public/server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/watchlists/eu/tags/CalendarTypeType.java:11: error: package javax.xml.bind.annotation does not exist
> import javax.xml.bind.annotation.XmlEnum;
>                                 ^
> /root/batm_public/server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/watchlists/eu/tags/CalendarTypeType.java:12: error: package javax.xml.bind.annotation does not exist
> import javax.xml.bind.annotation.XmlType;
>                                 ^
> /root/batm_public/server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/watchlists/eu/tags/CalendarTypeType.java:33: error: cannot find symbol
> @XmlType(name = "CalendarTypeType")
>  ^
>   symbol: class XmlType
> /root/batm_public/server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/watchlists/eu/tags/CalendarTypeType.java:34: error: cannot find symbol
> @XmlEnum
>  ^
>   symbol: class XmlEnum
> /root/batm_public/server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/watchlists/eu/tags/SubjectTypeClassificationCodeType.java:11: error: package javax.xml.bind.annotation does not exist
> import javax.xml.bind.annotation.XmlEnum;
>                                 ^
> /root/batm_public/server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/watchlists/eu/tags/SubjectTypeClassificationCodeType.java:12: error: package javax.xml.bind.annotation does not exist
> import javax.xml.bind.annotation.XmlType;
>                                 ^
> /root/batm_public/server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/watchlists/eu/tags/SubjectTypeClassificationCodeType.java:30: error: cannot find symbol
> @XmlType(name = "SubjectTypeClassificationCodeType")
>  ^
>   symbol: class XmlType
> /root/batm_public/server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/watchlists/eu/tags/SubjectTypeClassificationCodeType.java:31: error: cannot find symbol
> @XmlEnum
>  ^
>   symbol: class XmlEnum
> /root/batm_public/server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/watchlists/eu/tags/RegulationSummaryType.java:11: error: package javax.xml.bind.annotation does not exist
> import javax.xml.bind.annotation.XmlAccessType;
>                                 ^
> /root/batm_public/server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/watchlists/eu/tags/RegulationSummaryType.java:12: error: package javax.xml.bind.annotation does not exist
> import javax.xml.bind.annotation.XmlAccessorType;
>                                 ^
> /root/batm_public/server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/watchlists/eu/tags/RegulationSummaryType.java:13: error: package javax.xml.bind.annotation does not exist
> import javax.xml.bind.annotation.XmlAttribute;
>                                 ^
> /root/batm_public/server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/watchlists/eu/tags/RegulationSummaryType.java:14: error: package javax.xml.bind.annotation does not exist
> import javax.xml.bind.annotation.XmlType;
>                                 ^
> /root/batm_public/server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/watchlists/eu/tags/RegulationSummaryType.java:40: error: cannot find symbol
> @XmlAccessorType(XmlAccessType.FIELD)
>  ^
>   symbol: class XmlAccessorType
> /root/batm_public/server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/watchlists/eu/tags/RegulationSummaryType.java:41: error: cannot find symbol
> @XmlType(name = "RegulationSummaryType")
>  ^
>   symbol: class XmlType
> /root/batm_public/server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/watchlists/eu/tags/AdditionalInfoType.java:11: error: package javax.xml.bind.annotation does not exist
> import javax.xml.bind.annotation.XmlAccessType;
>                                 ^
> /root/batm_public/server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/watchlists/eu/tags/AdditionalInfoType.java:12: error: package javax.xml.bind.annotation does not exist
> import javax.xml.bind.annotation.XmlAccessorType;
>                                 ^
> /root/batm_public/server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/watchlists/eu/tags/AdditionalInfoType.java:13: error: package javax.xml.bind.annotation does not exist
> import javax.xml.bind.annotation.XmlAttribute;
>                                 ^
> /root/batm_public/server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/watchlists/eu/tags/AdditionalInfoType.java:14: error: package javax.xml.bind.annotation does not exist
> import javax.xml.bind.annotation.XmlType;
>                                 ^
> /root/batm_public/server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/watchlists/eu/tags/AdditionalInfoType.java:37: error: cannot find symbol
> @XmlAccessorType(XmlAccessType.FIELD)
>  ^
>   symbol: class XmlAccessorType
> /root/batm_public/server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/watchlists/eu/tags/AdditionalInfoType.java:38: error: cannot find symbol
> @XmlType(name = "AdditionalInfoType")
>  ^
>   symbol: class XmlType
> Note: Some input files use or override a deprecated API.
> Note: Recompile with -Xlint:deprecation for details.
> Note: Some input files use unchecked or unsafe operations.
> Note: Recompile with -Xlint:unchecked for details.
> 100 errors
> 
> > Task :server_extensions_extra:compileJava FAILED
> 
> FAILURE: Build failed with an exception.

**Comment by rpanak-generalbytes** [comment]
Hi,
it's a Java 8 project. Are you getting the errors with Java 8 as well?

**Comment by letreset** [comment]
We cannot install java8 sdk on ubuntu 18.04. java8 support removed from repository.
https://launchpad.net/~webupd8team/+archive/ubuntu/java

**Comment by rpanak-generalbytes** [comment]
We support only Java 8 (OpenJDK8 to be precise) and Ubuntu 16.04. You might want to use newer Ubuntu/Java versions for development (or even for production) and it may or may not work. However, we don't support those setups.

However, there are more ways to install Java 8 (or rather OpenJDK 8) than the webupd8 repo. AFAIK, there should be an official OpenJDK 8 package in ubuntu, or you can use SDKman (https://sdkman.io/; better choice for development environment)

**Comment by letreset** [comment]
Thanks for your response. It's only compiling java8.

**Comment by pvyhnal-generalbytes** [comment]
@olalonde yes that version should be fine
