### ISSUE TITLE
I'd like to update StableUSD's logo and name.

### ISSUE THREAD

**Issue by Stably-Blockchain** [GENERALBYTESCOM/batm_public#296]
We at Stably have recently rebranded, and would like to change our name to Stably Dollar and also update our logo to the one attached. 

Any help to accomplish this would be greatly appreciated!
![Mark_Standard](https://user-images.githubusercontent.com/38167996/68811765-3d963700-0626-11ea-9186-317698f1fe81.png)

**Comment by generalbytes** [comment]
Fork this repository. change an image in your repo. create a pull request. we review it and if it is ok we will merge it. If you don't know how to perform these tasks find some developer close to you to help you.
