### ISSUE TITLE
Sumcoin selling requiring operator overide

### ISSUE THREAD

**Issue by 5053s** [GENERALBYTESCOM/batm_public#313]
When selling Sumcoin the operator must manually approve a transaction for some reason.   This is possibly due to a fee issue?   The issue may have presented itself when SUM went from v0.16 to v0.17 and the only thing I have found that changed is the mandated fee per kb difference. 

The operator will receive the coin when the patron sends the SUM to the withdraw ticket, however the BATM will continue to tell the patron the "Withdraw not possible | Payment is on it's way"   - even though the transaction has settled on the blockchain.

I have been trying to trouble shoot this but have had no luck yet in solving what the issue is.   

Outside of this, Sumcoin has been the fastest coin and most stable overall coin I've ever seen to buy out of a GB ATM.

Please advise on the selling function.

**Comment by generalbytes** [comment]
I don't think this issue is valid. There shouldn't be required to do any sort of manual approval. Please contact regular support@generalbytes.com with this issue.
