### ISSUE TITLE
Adding currencies-1.0-SNAPSHOT.jar instructions to README

### ISSUE THREAD

**Issue by brandonbryant12** [GENERALBYTESCOM/batm_public#332]
It seems that you were modifying https://github.com/GENERALBYTESCOM/batm_public/blob/master/currencies/src/main/java/com/generalbytes/batm/common/currencies/CryptoCurrency.java
by adding RONC("RonCoin"), but you did't copy new currencies-1.0-SNAPSHOT.jar to /batm/app/master/lib

_Originally posted by @generalbytes in https://github.com/GENERALBYTESCOM/batm_public/issues/188#issuecomment-475114887_

It seems that you were modifying https://github.com/GENERALBYTESCOM/batm_public/blob/master/currencies/src/main/java/com/generalbytes/batm/common/currencies/CryptoCurrency.java
by adding RONC("RonCoin"), but you did't copy new currencies-1.0-SNAPSHOT.jar to /batm/app/master/lib

Where is currencies-1.0-SNAPSHOT.jar built to?

I build the project with ./gradlew build
and then search with grep -re currencies-1.0-SNAPSHOT.jar . and find nothing

**Comment by generalbytes** [comment]
Done.
