### ISSUE TITLE
For more security spongycastle -> bouncycastle

### ISSUE THREAD

**Issue by Neustradamus** [GENERALBYTESCOM/batm_public#352]
For more security, can you change old spongycastle (based on old bouncycastle) to bouncycastle?
- https://www.bouncycastle.org/
- https://www.bouncycastle.org/releasenotes.html
- http://www.bouncycastle.org/latest_releases.html
- https://www.cvedetails.com/vulnerability-list/vendor_id-7637/Bouncycastle.html

**Comment by generalbytes** [comment]
We no longer use spongycastle we use bouncycastle. I agree we should upgrade to bouncycastle version 1.65.

**Comment by Neustradamus** [comment]
@generalbytes: But Spongy Castle is always here :/
- https://github.com/GENERALBYTESCOM/batm_public/search?q=spongycastle&unscoped_q=spongycastle

**Comment by generalbytes** [comment]
Done in commit f74c45cbabe43d01350ea232d088241131097a58. Will be available in next release.

**Comment by generalbytes** [comment]
Spongy castle has to remain in checksums as spongycastle is a transitive dependency from dashj, bitcoinj etc. these libraries use spongycastle to avoid clash with android bouncycastle libraries.

**Comment by Neustradamus** [comment]
BitcoinJ and DashJ do not use Spongy Castle:
- https://github.com/bitcoinj/bitcoinj
- https://github.com/dashevo/dashj
- ...

**Comment by Neustradamus** [comment]
@generalbytes: There are CVEs in Spongy Castle here:
- https://github.com/GENERALBYTESCOM/batm_public/commit/1b5cdffd4c1f756dfb33c23013e1686429b62f7d

And the last version of Spongy Castle (with CVEs too) is 1.58.

**Comment by Neustradamus** [comment]
@generalbytes: There is a ticket here too:
- https://github.com/GENERALBYTESCOM/bitrafael_public/issues/36

**Comment by Neustradamus** [comment]
@generalbytes: But Spongy Castle is always here :/
- https://github.com/GENERALBYTESCOM/batm_public/search?q=spongycastle&unscoped_q=spongycastle

**Comment by Neustradamus** [comment]
@generalbytes: Can you remove old Spongy Castle code?
- https://github.com/GENERALBYTESCOM/batm_public/search?q=spongycastle&unscoped_q=spongycastle

And update Bouncy Castle to 1.69?
