### ISSUE TITLE
Error preparing transaction

### ISSUE THREAD

**Issue by makarid** [GENERALBYTESCOM/batm_public#359]
Hello, i am trying to call the sellCrypto() function in order to test it on my batm-server and i am getting this error message as a response:"Error preparing transaction.". I do not have any ATM active when i running it, does it matter? My parameters are:

ITransactionSellInfo sellInfo = context.sellCrypto("BT301430", BigDecimal.valueOf(20), "EUR", BigDecimal.valueOf(0.001), "BTC", "IMDMHVV3OOBHI8VX", null);

Is there something that i haven't put correctly? The error message is not very informative. Thank you

**Comment by makarid** [comment]
Here is the error that i am getting on the log:

WARN | [»BT301435*/prepareTransaction2/103] batm.master.TPCryptoAndAltcoins - prepareTransaction3 - invalid token
-- | --
04/24/2020 12:40:33 PM | ERROR | [»BT301435*/prepareTransaction2/103] org.bitcoinmat.RESTSecuredService - sellCrypto - Error preparing transaction.com.generalbytes.batm.server.extensions.exceptions.SellException: sellCrypto - Error preparing transaction.at com.generalbytes.batm.server.extensions.a.a.a(GB:112)at com.generalbytes.batm.server.extensions.g.sellCrypto(GB:313)at org.bitcoinmat.batm.server.extensions.RESTSecuredService.sellCrypto(RESTSecuredService.java:65)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.lang.reflect.Method.invoke(Method.java:498)at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144)at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161)at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:205)at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99)at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389)at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347)at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102)at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326)at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)at org.glassfish.jersey.internal.Errors.process(Errors.java:315)at org.glassfish.jersey.internal.Errors.process(Errors.java:297)at org.glassfish.jersey.internal.Errors.process(Errors.java:267)at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305)at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154)at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:473)at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:427)at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:388)at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:341)at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:228)at com.generalbytes.batm.server.services.web.l.service(GB:96)at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:812)at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669)at com.generalbytes.batm.server.services.web.a.a.doFilter(GB:23)at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:221)at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)at org.eclipse.jetty.server.Server.handle(Server.java:499)at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:258)at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)at com.generalbytes.batm.server.services.web.s.a(GB:58)at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)at java.lang.Thread.run(Thread.java:748)

**Comment by makarid** [comment]
Right now i do not have any active ATM and i don't have provide the GB api key on the batm-server. Can i test the sellCrypto function without the above?

**Comment by generalbytes** [comment]
1. What is the server version? I would like to evaluate stacktrace that you provided.
2. How come that you do have server license but no ATM?

**Comment by makarid** [comment]
Hello
1. my version is  20200406.
2. i am trying to implement new functionality for my friends ATM network. I just want to test my endpoints without connecting to any ATM(the new functionality doesn't need ATMs)

In order to test the new functionality i need to make some "fake" sell transaction.

**Comment by makarid** [comment]
Hello, i have just add a correct API key but again the fake transaction that i want to test doesn't work with the same error message. My ATMs are not active

**Comment by generalbytes** [comment]
Please provide screenshot of whole configuration of terminal BT301430 from your admin panel.
It seem that machine with serial number BT301430 was never connected to your server.

Server's internal code has a check that it has to know the terminal software version before performing sell. Because you never had a machine BT301430 connected to a server it couldn't determine terminal software version.
Most likely your master log file also contains message "validateTokenInternal - Validation(incorrect params)."

**Comment by makarid** [comment]
Thank you so much for your response. Yes, the ATM is offline. In order the sellCrypto function to work properly i MUST have the ATM specified in parameters connected to the server? Is there a function to just add a transaction on the batm database without any ATM to be online? I thought to add a dummy transaction via mysql cli but there are a lot of tables that have transaction on their name and i don't know which one to create a row.

**Comment by generalbytes** [comment]
ATM doesn't have to be online. It just have to connect to ATM server at least once in server's history. No transaction is needed. Just the initial pairing has to be performed.
