### ISSUE TITLE
Find customer's transactions by public_id

### ISSUE THREAD

**Issue by makarid** [GENERALBYTESCOM/batm_public#370]
Hello, i would like to find all customer's transactions when he provides to me his phone number. I have write the following code in order to do that:

try {
            List<IIdentity> identityByPhoneNumber = RESTExtension.getExtensionContext().findIdentityByPhoneNumber(phoneNumber, null);
            if(identityByPhoneNumber.size() == 0){
                return new ResponseDTO(1,"This phone number doesn't exists in database.");
            }

          String transactionList = RESTExtension.getExtensionContext().findAllTransactionsByIdentityId(identityByPhoneNumber.get(0).getPublicId()).toString();
            return new ResponseDTO(0, transactionList);
        }catch (Exception e){
            log.error(e.getMessage(),e);
            return new ResponseDTO(1,"An error occured: "+e.getMessage());
        }

Here is the issue that i have encounter. I called the sellCrypto() function in order to add a dummy transaction. I have put the public id of my customer in the sellCrypto parameter. The public id is a string like "KSJDLSJS689SS". The problem is that on the table named transactionrecords the field type on the identity_id is bigint and not varchar. Because of that when i called the sellCrypto function, the database didn't add any identityPublic_id on the table, it added just a NULL value. So, when i call the findIdentityByPhoneNumber, i get correctly the identity with that phone number. But when i put the identity's id on the findAllTransactionsByIdentityId, the response is empty, because there isn't any public_id on transactionrecords table. The identity's public id is varchar and the transactionrecord.public_id is bigint.

**Comment by makarid** [comment]
Next i thought that with public_id you were referring to the id of the identity, which is the auto_incremental value of every row. But there is no way to call that value and test it using the findIdentityByPhoneNumber.

**Comment by generalbytes** [comment]
Every identity has database id and publicId. PublicId is the string that starts with 'I' letter.
You are saying: "The identity's public id is varchar and the transactionrecord.public_id is bigint."
There is no field transactionrecord.public_id. There is identity_id which is identity.id not identity.publicid.

Please do not rely on database id buy only on publicid.

**Comment by makarid** [comment]
OK, but how can i get the identity.id when i call the findIdentityByPhoneNumber function. There isn't any option to get that data in order to provide it to the findAllTransacionsByIdentityId function.
