### ISSUE TITLE
 Cannot submit transaction by extension for terminal BT301435 error

### ISSUE THREAD

**Issue by makarid** [GENERALBYTESCOM/batm_public#376]
05/18/2020 08:22:51 AM | DEBUG | [»BT301435/prepareTransaction2/130] batm.master.ExtensionContext - sellCrypto - Submitting sell transaction: 5 EUR
-- | -- | --
05/18/2020 08:22:51 AM | DEBUG | [»BT301435/submitTransaction2/130] batm.master.TPCryptoAndAltcoins - submitTransactionSellCrypto
05/18/2020 08:22:51 AM | WARN | [»BT301435/submitTransaction2/130] batm.master.TPCryptoAndAltcoins - submitTransactionSellCrypto - nulls
05/18/2020 08:22:51 AM | ERROR | [»BT301435/submitTransaction2/130] org.bitcoinmat.RESTSecuredService - sellCrypto - Cannot submit transaction by extension for terminal BT301435.com.generalbytes.batm.server.extensions.exceptions.SellException: sellCrypto - Cannot submit transaction by extension for terminal BT301435.at com.generalbytes.batm.server.extensions.a.a.a(GB:142)at com.generalbytes.batm.server.extensions.g.sellCrypto(GB:357)at org.bitcoinmat.batm.server.extensions.RESTSecuredService.sellCrypto(RESTSecuredService.java:68)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.lang.reflect.Method.invoke(Method.java:498)at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144)at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161)at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:205)at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99)at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389)at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347)at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102)at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326)at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)at org.glassfish.jersey.internal.Errors.process(Errors.java:315)at org.glassfish.jersey.internal.Errors.process(Errors.java:297)at org.glassfish.jersey.internal.Errors.process(Errors.java:267)at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305)at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154)at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:473)at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:427)at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:388)at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:341)at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:228)at com.generalbytes.batm.server.services.web.l.service(GB:96)at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:812)at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669)at com.generalbytes.batm.server.services.web.a.a.doFilter(GB:23)at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:221)at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)at org.eclipse.jetty.server.Server.handle(Server.java:499)at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:258)at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)at com.generalbytes.batm.server.services.web.s.a(GB:59)at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)at java.lang.Thread.run(Thread.java:748)

**Comment by makarid** [comment]
Hello, for some reason when i call sellCrypto function from my Extension rest api i get this error. Can you please tell me why? Thanks

**Comment by makarid** [comment]
05/21/2020 10:38:50 AM | INFO | [»/TaskManager-worker-BitcoinPaymentSupport-PaymentRequestTimeoutInvalidator/106] batm.master.BitcoinPaymentSupport - PaymentRequestTimeoutInvalidatorTask.onDoStep - Checking for timed out requests
-- | -- | --
05/21/2020 10:39:08 AM | INFO | [»/DB-threadDBUpdater/14] c.g.batm.server.services.a.g - Updating one batch of TransactionExpenses
05/21/2020 10:39:23 AM | DEBUG | [»/WS-UNKNOWN/38905] batm.master.ExtensionContext - sellCrypto - Preparing transaction sell by extension for terminal BT301435...
05/21/2020 10:39:23 AM | INFO | [»BT301435/prepareTransaction2/38905] batm.master.TPCommon - Event: TRANSACTION PREPARED 0.00 EUR
05/21/2020 10:39:23 AM | DEBUG | [»BT301435/prepareTransaction2/38905] batm.common.TransactionLimits - Sell Transaction Limits (BT301435, identity = ANON, cryptoAddress = null):entry_cptr = 50.00 EUR \| result_cptr = 50.00 EUR (Limit per Transaction)entry_cph = 50.00 EUR \| cashInLastHour = 0.00 EUR \| result_cph = 50.00 EUR (Limit per hour)entry_cpd = 50.00 EUR \| cashInDay = 0.00 EUR \| result_cpd = 50.00 EUR (Limit per day)entry_cpda = 50.00 EUR \| cashInDayForAddress = 0.00 EUR \| result_cpda = 50.00 EUR (Limit per day for address)entry_cpdt = 1,000.00 EUR \| cashInDayForTerminal = 0.00 EUR \| result_cpdt = 1,000.00 EUR (Limit per day for Terminal)entry_cpw = 50.00 EUR \| cashInWeek = 0.00 EUR \| result_cpw = 50.00 EUR (Limit per week)entry_cpm = 50.00 EUR \| cashInMonth = 0.00 EUR \| result_cpm = 50.00 EUR (Limit per month)entry_cp3m = 50.00 EUR \| cashIn3Month = 0.00 EUR \| result_cp3m = 50.00 EUR (Limit per 3 months)entry_cp12m = 50.00 EUR \| cashIn12Month = 0.00 EUR \| result_cp12m = 50.00 EUR (Limit per 12 months)entry_cpq = 50.00 EUR \| cashInQuarter = 0.00 EUR \| result_cpq = 50.00 EUR (Limit per calendar year quarter)entry_cpy = 50.00 EUR \| cashInYear = 0.00 EUR \| result_cpy = 50.00 EUR (Limit per calendar year)entry_ctpa = 50.00 EUR \| cashTotalPerAddress = 0.00 EUR \| result_ctpa = 50.00 EUR (Total cash limit per crypto address)entry_ct = Not Set \| cashTotal = 0.00 EUR \| result_ct = No Limit (Total Identity Limit)RESULTING LIMIT = 50.00 EUR
05/21/2020 10:39:23 AM | DEBUG | [»BT301435/prepareTransaction2/38905] batm.master.ExtensionContext - sellCrypto - Submitting sell transaction: 5 EUR
05/21/2020 10:39:23 AM | DEBUG | [»BT301435/submitTransaction2/38905] batm.master.TPCryptoAndAltcoins - submitTransactionSellCrypto
05/21/2020 10:39:23 AM | WARN | [»BT301435/submitTransaction2/38905] batm.master.TPCryptoAndAltcoins - submitTransactionSellCrypto - nulls
05/21/2020 10:39:23 AM | ERROR | [»BT301435/submitTransaction2/38905] org.bitcoinmat.RESTSecuredService - sellCrypto - Cannot submit transaction by extension for terminal BT301435.com.generalbytes.batm.server.extensions.exceptions.SellException: sellCrypto - Cannot submit transaction by extension for terminal BT301435.at com.generalbytes.batm.server.extensions.a.a.a(GB:142)at com.generalbytes.batm.server.extensions.g.sellCrypto(GB:357)at org.bitcoinmat.batm.server.extensions.RESTSecuredService.sellCrypto(RESTSecuredService.java:68)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.lang.reflect.Method.invoke(Method.java:498)at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144)at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161)at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:205)at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99)at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389)at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347)at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102)at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326)at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)at org.glassfish.jersey.internal.Errors.process(Errors.java:315)at org.glassfish.jersey.internal.Errors.process(Errors.java:297)at org.glassfish.jersey.internal.Errors.process(Errors.java:267)at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305)at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154)at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:473)at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:427)at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:388)at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:341)at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:228)at com.generalbytes.batm.server.services.web.l.service(GB:96)at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:812)at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669)at com.generalbytes.batm.server.services.web.a.a.doFilter(GB:23)at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:221)at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)at org.eclipse.jetty.server.Server.handle(Server.java:499)at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:258)at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)at com.generalbytes.batm.server.services.web.s.a(GB:59)at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)at java.lang.Thread.run(Thread.java:748)
05/21/2020 10:39:27 AM | DEBUG | [»/TaskManager-worker-PaymentRequestTimeoutInvalidator-BCH/106] batm.master.TaskMgr - performStep - Executing step of task PaymentRequestTimeoutInvalidator-BCH
05/21/2020 10:39:27 AM | INFO | [»/TaskManager-worker-PaymentRequestTimeoutInvalidator-BCH/106] batm.master.RPCPaymentSupport - BCH: PaymentRequestTimeoutInvalidatorTask.onDoStep - Checking for timed out requests

**Comment by generalbytes** [comment]
Some of the mandatory parameters that you provide to function are null.
Check all of the properties of the objects that you provide to function. Some of them is null.
For further investigation please write here also contains of all parameters.

**Comment by makarid** [comment]
Hello, you are right i had the cryptoAmount field null. I had it null because on the comments on sellCrypto function, you are writing: "ignored- reserved for future". When you have time can you delete that to prevent further confusion in the future. Thanks a lot!

**Comment by generalbytes** [comment]
Fixed here.
https://github.com/GENERALBYTESCOM/batm_public/commit/19aab253d1132ee8e35ba9861ef970cc2ed27910
