### ISSUE TITLE
Not able to Integrate my own ERC20 token 

### ISSUE THREAD

**Issue by anujdhiman** [GENERALBYTESCOM/batm_public#396]
Hi Team, 
First of all I appreciate of your good job.

I would like to tell you that i have my own Crypto Token named 'Bizzcoin'  and i want to integrate it in the CAS server.
I have followed all steps given its Readme documentation. There is a already Dai ERC20 token implemented in code. In the same way I have configured Bizz Token and created its relevant files in 'Server_extensions_extra' folder. When I created its Jar file after adding new extension and deployed on my server. But problem is i can see that currency in currency drop down in that way as already. Let suppose btc - Bitcoin, in the same way my currency should be "bizz-Bizzcoin" .But I am getting only BIZZ. and once currency is created i am not able to fetch its source buy rate(TESTS).
Please suggest me How to resolve this problem ASAP. I will be very thankful for your quick response.

Thanks

**Comment by generalbytes** [comment]
Write here a link to your fork so we can see what you have.

**Comment by anujdhiman** [comment]
Thanks for your response.
Please check my Github link where i have made change regarding my own Bizz Token and suggest me where i would need to correct the code ?
[https://github.com/surindergiri/batm_public/tree/BIZZ](url)

**Comment by anujdhiman** [comment]
![Screenshot from 2020-07-13 13-36-29](https://user-images.githubusercontent.com/5501736/88041914-ba3fc480-cb68-11ea-979b-f3ae0efdbd6d.png)
this is drop down in which currency is not in right format.

when i test  by RUN BIZZ SETTING TESTS >> TEST RATE SOURCE BUY

It displays this error given below - 
![Screenshot from 2020-07-21 15-52-49](https://user-images.githubusercontent.com/5501736/88043398-012eb980-cb6b-11ea-9385-b52905f674b6.png)

**Comment by generalbytes** [comment]
Please submit the screenshot of whole page not just part of it.

**Comment by anujdhiman** [comment]
1. It seems like 'currencies-1.0-SNAPSHOT.jar'  has some problem. when i replace this file with my own then i am getting an error shown below - 

![Screenshot from 2020-07-21 13-36-47](https://user-images.githubusercontent.com/5501736/88057412-abb0d780-cb7f-11ea-90f9-76df70eb3928.png)

2. Screenshot of currency missing - 

![screencapture-3-17-202-80-7777-2020-07-21-18_20_20](https://user-images.githubusercontent.com/5501736/88056954-0138b480-cb7f-11ea-95bc-e2467108e1e2.png)

3. 
![screencapture-3-17-202-80-7777-2020-07-21-18_27_38](https://user-images.githubusercontent.com/5501736/88057677-08ac8d80-cb80-11ea-8b0a-8b14633c7937.png)

![screencapture-3-17-202-80-7777-2020-07-21-18_28_06](https://user-images.githubusercontent.com/5501736/88057705-1104c880-cb80-11ea-84a2-8a33348173b8.png)

**Comment by anujdhiman** [comment]
any update please ?

**Comment by generalbytes** [comment]
Please provide also master.log

**Comment by anujdhiman** [comment]
![Screenshot from 2020-07-22 18-02-07](https://user-images.githubusercontent.com/5501736/88176832-8090bb80-cc45-11ea-9cb1-dd847ceedb3a.png)

**Comment by anujdhiman** [comment]
do you need any thing  else from our side. we are stuck. Please resolve it ASAP.

**Comment by anujdhiman** [comment]
Please have a look on it ASAP. We have to lunch it after 20 hours. it is very urgent.

**Comment by generalbytes** [comment]
"NoSuchFieldError: BIZZ" indicates that some library expects another library to contain field BIZZ but it is not there.
I believe you need to replace /batm/app/master/lib/currencies-1.0-SNAPSHOT.jar with one that you modified (added BIZZ)

**Comment by anujdhiman** [comment]
It seems like 'currencies-1.0-SNAPSHOT.jar' has some problem. when i replace this file with my own then i am getting an error shown below -

https://user-images.githubusercontent.com/5501736/88057412-abb0d780-cb7f-11ea-90f9-76df70eb3928.png

**Comment by generalbytes** [comment]
It is impossible to find out the issue without providing admin.log. Please contact regular support dpt. via support@generalbytes.com They will ask you for the log files.
