### ISSUE TITLE
Build failed 

### ISSUE THREAD

**Issue by anujdhiman** [GENERALBYTESCOM/batm_public#398]
I have downloaded the code from Master branch and trying to build it by the command - ./gradlew build
it could not be success showing following errors-

`
> Task :server_extensions_extra:test

com.generalbytes.batm.server.extensions.extra.dash.sources.coinmarketcap.CoinmarketcapAPITest > getTickerDogecoinTest FAILED
    java.net.SocketTimeoutException at CoinmarketcapAPITest.java:62

com.generalbytes.batm.server.extensions.extra.dash.sources.coinmarketcap.CoinmarketcapAPITest > getQuotesTest FAILED
    java.net.SocketTimeoutException at CoinmarketcapAPITest.java:93

com.generalbytes.batm.server.extensions.extra.dash.sources.coinmarketcap.CoinmarketcapAPITest > jsonTest FAILED
    java.net.SocketTimeoutException at CoinmarketcapAPITest.java:28

com.generalbytes.batm.server.extensions.extra.dash.sources.coinmarketcap.CoinmarketcapAPITest > getTickerOneIntegerOneStringParametersTest FAILED
    java.net.SocketTimeoutException at CoinmarketcapAPITest.java:53

com.generalbytes.batm.server.extensions.extra.dash.sources.coinmarketcap.CoinmarketcapAPITest > getTickerOneIntegerOneNullParametersTest FAILED
    java.net.SocketTimeoutException at CoinmarketcapAPITest.java:80

com.generalbytes.batm.server.extensions.extra.dash.sources.coinmarketcap.CoinmarketcapAPITest > getQuoteByCurrencySymbolAndFiatCurrencyTest FAILED
    java.net.SocketTimeoutException at CoinmarketcapAPITest.java:119

75 tests completed, 6 failed, 35 skipped

> Task :server_extensions_extra:test FAILED
`

Please have a look on it. not able to make build.

Thanks

**Comment by makarid** [comment]
I have the same errors

**Comment by surindergiri** [comment]
I am also facing the same issue @makarid did you figure this out?

**Comment by TheSohit** [comment]
facing same issue. need help urgently

**Comment by makarid** [comment]
I really do not understand why this is happening. I change API_KEY and it still doesn't work. I get response only if i send a request with API_KEY = null. I check in my coinmarketcap api account to see how many requests i have send so far and it is always zero.It is like the request never reaches their server

**Comment by makarid** [comment]
I think the issue in the part of coinmarketcap. They send response if you send an invalid request, but if you send a good request they don't response.

**Comment by generalbytes** [comment]
Fixed in https://github.com/GENERALBYTESCOM/batm_public/pull/404
