### ISSUE TITLE
Issue closed without fixing "Not able to Integrate my own ERC20 token #396"

### ISSUE THREAD

**Issue by anujdhiman** [GENERALBYTESCOM/batm_public#401]
We will have a launch in 40 countries and almost 400+ machines we are buying in Future
But, not totally stuck on your support as unable to cover up the issue for very first machine setup. Kindly, involve someone to look and provide your support on priority basis as we had a Launch planning in Spain by tomorrow. 

Please check this from my old closed issues:-
https://github.com/GENERALBYTESCOM/batm_public/issues/396#issuecomment-661845613

**Comment by anujdhiman** [comment]
Please don't close without our confirmation. This is my contact no. +916239719955 in case you require.

**Comment by generalbytes** [comment]
Please note that this is not a sales department customer support. This is not a channel where business critical issues should be reported and resolved.  
If you have purchased machines in past and you paid your support please use support@generalbytes.com or generalbytes customer portal to get your issues resolved.

This is place where developers help a developer. Not a support department.
