### ISSUE TITLE
Generated Currencies-1.0-SNAPSHOT.jar giving issue

### ISSUE THREAD

**Issue by anujdhiman** [GENERALBYTESCOM/batm_public#402]
Hi Developers,

I am  trying to upload my currencies-1.0-SNAPSHOT.jar file on CAS server but getting this below error:-

![88057412-abb0d780-cb7f-11ea-90f9-76df70eb3928](https://user-images.githubusercontent.com/5501736/88294154-89eb5800-cd19-11ea-881f-9d4f45d4f2ab.png)

**Comment by shashiantier** [comment]
Team, any update on this.

**Comment by generalbytes** [comment]
Please contact support@generalbytes.com they will ask you for logs.
