### ISSUE TITLE
Not able to Integrate my own ERC20 token

### ISSUE THREAD

**Issue by anujdhiman** [GENERALBYTESCOM/batm_public#403]
Hello Developers,

I am replacing my generated 'currencies-1.0-SNAPSHOT.jar' file on the server. But i am getting the same issue as in the link:- 
https://github.com/GENERALBYTESCOM/batm_public/issues/396#issuecomment-661845613

Please suggest me How to resolve this problem ASAP. I will be very thankful if anybody can help me in resolving this issue.

**Comment by generalbytes** [comment]
This is not a chat system where you create for each sentence new issue. 
Contact support@generalbytes.com
