### ISSUE TITLE
Question about the addIdentity function

### ISSUE THREAD

**Issue by makarid** [GENERALBYTESCOM/batm_public#406]
Hello, i have some questions about the parameters of the addIdentity function that you have on the IExtensionContext. Can you please tell me what are the following parameters(i mean what they are doing): 

1) what is the "external" parameter, what i need to put in it?
2) why i need to provide the terminalNumber in order to create an identity? Is the creation of an identity visible to every terminal in my organisation? If i create an identity with terminal X will be visible for terminal Y?
3) Does the limits apply to every fiat currency or only to the currency that i have put on the configurationCashCurrency param? Thanks

**Comment by pvyhnal-generalbytes** [comment]
1. external ID can be anything your system uses. It will be saved and can be used by your extension later. You don't need to put anything in
1. The terminal serial number identifies a terminal that was used to register the identity if it was registered on a terminal. Unfortunately it cannot be currently left blank when creating an identity from an extension. Use any of your terminals. Created identities are shared in your Organization.
1. configurationCashCurrency is the currency used in Identity's limits

**Comment by makarid** [comment]
Thank you for the reply @pvyhnal-generalbytes .
