### ISSUE TITLE
Bitpanda PRO Exchange

### ISSUE THREAD

**Issue by doscoinway** [GENERALBYTESCOM/batm_public#407]
Hi, we get following error: "error_code": "BAD_AMOUNT_PRECISION",

**Comment by makarid** [comment]
Probably this has to do with the Bitpanda PRO Exchange. They use a specific precision amount lets say 2 decimal places. So if you send an order with 3 decimal places then it will through this error.

**Comment by pyranja** [comment]
Hi @doscoinway ,

There is an error code reference in the [api documentation](https://developers.bitpanda.com/exchange/#error-codes).

`BAD_AMOUNT_PRECISION` signals the the amount of the order that should be created is exceeding the allowed values.
Accepted precisions for each market can be retrieved from https://api.exchange.bitpanda.com/public/v1/instruments , each instrument has a field `amount_precision`.
For example `BTC/EUR` accepts amounts with up to 5 decimal places.

I'd kindly ask you to share details on the rejected order, if you think that the order should have been accepted.

Disclaimer: I'm an employee of Bitpanda.

**Comment by doscoinway** [comment]
Hi @pyranja,

we are testing in live the implementattion Exchange Bitpanda PRO in batm_public general bytes. There is now option to set decimal places. I think ist must be set in the implementation?

Thanks for answering!

**Comment by pvyhnal-generalbytes** [comment]
Should be fixed in #410 
After fixing BAD_AMOUNT_PRECISION, BAD_PRICE_PRECISION was returned too.
@pyranja does the change seem fine to you? I hardcoded the precision values for now, they shouldn't change often, right?

**Comment by pyranja** [comment]
@pvyhnal-generalbytes 

> does the change seem fine to you? I hardcoded the precision values for now, they shouldn't change often, right?

Scaling the amount looks good, except for one precision value.
These values are not expected to change.

w.r.t. to the price precision I found a bug in the calculation of limit order prices, that likely causes this.
I'm preparing a PR with both fixes.

**Comment by pyranja** [comment]
I've pushed #411 which includes the fix to round crypto amounts to the allowed precision and a fix for the wrong price calculation.

:exclamation: the fix for price calculation is important as the initial implementation can create orders with inappropriate prices.
