### ISSUE TITLE
Adding new token issue

### ISSUE THREAD

**Issue by makarid** [GENERALBYTESCOM/batm_public#408]
Hello, i am trying to add a new token on my server but i get the following errors on the admin logs:

08/11/2020 11:30:50 AM	WARN	
[src/_views/crypto_settings/form.jsp] (default task-9) error - get crypto currency name for TOKEN1
08/11/2020 11:30:55 AM	WARN	
[src/ajax/terminal_action_crypto.jsp] (default task-9) error - get crypto currency name for TOKEN1
08/11/2020 11:31:18 AM	INFO	
[src/_views/crypto_settings/process.jsp] (default task-12) Crypto Setting 'TOKEN1' was modified by 'admin'
08/11/2020 11:31:36 AM	WARN	
[src/_views/terminals/form.jsp] (default task-9) error - get crypto currency name for TOKEN1
08/11/2020 11:32:09 AM	INFO	
[src/_views/terminals/process_modify.jsp] (default task-9) Terminal 'BTXXXXX' was modified by 'admin'
08/11/2020 11:32:18 AM	WARN	
[src/_views/terminals/form.jsp] (default task-9) error - get crypto currency name for TOKEN1
08/11/2020 11:32:51 AM	WARN	
[src/_views/terminals/form.jsp] (default task-15) error - get crypto currency name for TOKEN1
08/11/2020 11:46:59 AM	WARN	
[src/_views/terminals/form.jsp] (default task-30) error - get crypto currency name for TOKEN1
08/11/2020 12:21:57 PM	WARN	
[src/_views/terminals/form.jsp] (default task-49) error - get crypto currency name for TOKEN1

Do you know a possible reason for that error? The message is not very helpful. Thanks

**Comment by generalbytes** [comment]
most likely you didn't copy your modified version currencies-1.0-SNAPSHOT.jar into master.

**Comment by makarid** [comment]
i have added my modified currencies.jar on the master/lib folder. Is it the correct folder?
