### ISSUE TITLE
No Logo for ILCoin

### ISSUE THREAD

**Issue by PlusBitPos** [GENERALBYTESCOM/batm_public#417]
Hello BATM team, 
Today we activated ILCoin, however the logo disappear on the screen, what can be the problem? Please see attached file
Best regards

**Comment by PlusBitPos** [comment]
This is our PR: https://github.com/GENERALBYTESCOM/batm_public/pull/405

Here is issue image: https://imgur.com/gallery/iD6qMHa

**Comment by PlusBitPos** [comment]
This is our PR: https://github.com/GENERALBYTESCOM/batm_public/pull/405

Here is issue image: https://imgur.com/gallery/iD6qMHa

**Comment by PlusBitPos** [comment]
This is our PR: https://github.com/GENERALBYTESCOM/batm_public/pull/405

Here is issue image: https://imgur.com/gallery/iD6qMHa

**Comment by PlusBitPos** [comment]
This is our PR: https://github.com/GENERALBYTESCOM/batm_public/pull/405

Here is issue image: https://imgur.com/gallery/iD6qMHa

**Comment by PlusBitPos** [comment]
This is our PR: https://github.com/GENERALBYTESCOM/batm_public/pull/405

Here is issue image: https://imgur.com/gallery/iD6qMHa

**Comment by PlusBitPos** [comment]
This is our PR: https://github.com/GENERALBYTESCOM/batm_public/pull/405

Here is issue image: https://imgur.com/gallery/iD6qMHa

**Comment by PlusBitPos** [comment]
This is our PR: https://github.com/GENERALBYTESCOM/batm_public/pull/405

Here is issue image: https://imgur.com/gallery/iD6qMHa

**Comment by PlusBitPos** [comment]
This is our PR: https://github.com/GENERALBYTESCOM/batm_public/pull/405

Here is issue image: https://imgur.com/gallery/iD6qMHa

**Comment by PlusBitPos** [comment]
This is our PR: https://github.com/GENERALBYTESCOM/batm_public/pull/405

Here is issue image: https://imgur.com/gallery/iD6qMHa

**Comment by PlusBitPos** [comment]
This is our PR: https://github.com/GENERALBYTESCOM/batm_public/pull/405

Here is issue image: https://imgur.com/gallery/iD6qMHa

**Comment by PlusBitPos** [comment]
This is our PR: https://github.com/GENERALBYTESCOM/batm_public/pull/405

Here is issue image: https://imgur.com/gallery/iD6qMHa

**Comment by PlusBitPos** [comment]
This is our PR: https://github.com/GENERALBYTESCOM/batm_public/pull/405

Here is issue image: https://imgur.com/gallery/iD6qMHa

**Comment by PlusBitPos** [comment]
This is our PR: https://github.com/GENERALBYTESCOM/batm_public/pull/405

Here is issue image: https://imgur.com/gallery/iD6qMHa

**Comment by PlusBitPos** [comment]
This is our PR: https://github.com/GENERALBYTESCOM/batm_public/pull/405

Here is issue image: https://imgur.com/gallery/iD6qMHa

**Comment by PlusBitPos** [comment]
This is our PR: https://github.com/GENERALBYTESCOM/batm_public/pull/405

Here is issue image: https://imgur.com/gallery/iD6qMHa

**Comment by PlusBitPos** [comment]
Any help about issue?

**Comment by PlusBitPos** [comment]
Any help about issue?

**Comment by PlusBitPos** [comment]
Any help about issue?

**Comment by PlusBitPos** [comment]
Any help about issue?

**Comment by generalbytes** [comment]
Problem is most likely in SVG file.
Your SVG file probably contains tags not supported by SVG android library that BATM uses ( https://bigbadaboom.github.io/androidsvg/ ) or it has wrong resolution/viewport. Compare contains of your SVG file with other cryptocurrency SVG files that work.
You can also try some android examples from mentioned library on your android phone with your SVG file to tackle the issue.

**Comment by PlusBitPos** [comment]
Thank you, we can close the issue, i have submitted PR for new SVG file
Best regards
