### ISSUE TITLE
Generating Withdrawals Externally

### ISSUE THREAD

**Issue by alexandrubujor** [GENERALBYTESCOM/batm_public#418]
We want to create an extension that will allow the users to generate withdrawals online on our website and cash-out at the ATM once their transaction is confirmed. Which extension interface will allow the creation of withdrawals externally? 

Ideally we want to just be able to generate a withdrawal and get the deposit address. The confirmation should come through the blockchain monitoring only or CAS web-based operations (So not via API).

Thanks!

**Comment by generalbytes** [comment]
Check following methods. It should enable you to find terminal with available cash as well as to calculate correct amount and get withdrawal address.
IExtensionContext.sellCrypto
IExtensionContext.calculateCashAvailableForSell
IExtensionContext.getAvailableBanknotesConsideringFutureWithdrawals
IExtensionContext.findTerminalsWithAvailableCashForSell

You may want to also take a look at: RESTServiceExample.java

**Comment by makarid** [comment]
What checks does the sellCrypto function internally? Thanks

**Comment by generalbytes** [comment]
Creates gets depositaddress, generates receipt, monitors incoming payment. Same thing as SELL functionality on physical two-way machine(BATM3/BATM4).
