### ISSUE TITLE
IExtensionContext.addIdentity question

### ISSUE THREAD

**Issue by makarid** [GENERALBYTESCOM/batm_public#419]
Hello, i would like to ask you why on this function (addIdentity) i need to give a List of ILimits and why not just one ILimit object. Can i add more ILimits for the same configuration currency? Thanks

**Comment by makarid** [comment]
Will you answer me at some point? Thanks

**Comment by generalbytes** [comment]
Your ATM may be accepting multiple fiat currencies such as USD and EUR. 
You may specify different limit for each fiat currency. This is helpful when you want to have a round values.
