### ISSUE TITLE
Implementing IPaymentSupport issue

### ISSUE THREAD

**Issue by makarid** [GENERALBYTESCOM/batm_public#427]
Hello, in order to implement a withdraw option for a coin we must implement the IPaymentSupport interface. My question is, how can i get the address of the user that sends the funds to my paymentAddress? Is that possible in the IPaymentSupport interface? I want to get the address that the user send the funds from in order to check if i get the funds from this particular address. I couldn't find any function or parameter that gives this information.Thanks

**Comment by makarid** [comment]
Can someone help me with this. Thanks

**Comment by kingofnorthamerica** [comment]
Held by company private usa citizens only

**Comment by pvyhnal-generalbytes** [comment]
Hi, in general you should generate new address for every incoming payment and check if the correct amount was received to the address. See existing implementations of IPaymentSupport for different ways to do it

**Comment by makarid** [comment]
Thanks. I will close the issue
