### ISSUE TITLE
IRemainingLimits getType information required

### ISSUE THREAD

**Issue by makarid** [GENERALBYTESCOM/batm_public#443]
Hello, i would like to get what limits remaining for a particular identity. I call the context.getIdentityRemainingLimits() function and i get a response of a List "IRemainingLimit". IRemainingLimit has 2 methods getAmount and getType, but there isn't any information about what this getType return code should be. I thing you need to change the getType return signature from String to Enum in order to see what these types are all about. Is it possible to do that? If not can you clarify what code types exists in order to get the ones that i want to query? Thanks

**Comment by generalbytes** [comment]
See following newly added javadoc: https://github.com/GENERALBYTESCOM/batm_public/commit/08243203b2f4bab1b33166f8388743b19a6b5e15
