### ISSUE TITLE
About List<IRemainingLimit> getIdentityRemainingLimits(String fiatCurrency, String terminalSerialNumber, String identityPublicId);

### ISSUE THREAD

**Issue by makarid** [GENERALBYTESCOM/batm_public#446]
Hello, thank you for providing comments for the limit type. I would like to ask you if it is possible to change the return type of this function from List to HashMap in order to get the limit type that we want to use without searching all the list. You can do something like that:

RemainingLimitType can be an enum
BigDecimal will be the amount

HashMap<RemainingLimitType,BigDecimal> getIdentityRemainingLimits(String fiatCurrency, String terminalSerialNumber, String identityPublicId);

Is that possible; Thanks

**Comment by generalbytes** [comment]
No, we are sorry. There might be more ways to look on limits then just by limit type. Please write a helper class in your extension to resolve your request.
