### ISSUE TITLE
ITransactionListener callbacks not being called

### ISSUE THREAD

**Issue by alexisdevtailor** [GENERALBYTESCOM/batm_public#451]
Hello,

I am Alexis Azanza, a developer for DagCoin in VisionCraft working under mikk.laos@visioncraft.ee.
My question is about the Java code of batm.
Our extension implemented the com.generalbytes.batm.server.extensions.ITransactionListener interface.
I noticed that isTransactionApproved() method is not being called when we call IWallet.sendCoins(). From my understanding, isTransactionApproved() should be called before sendCoins(). Is this correct? If not, how do we use this interface and make sure it is going to be called by the server? 
Basically we need to be able to get the terminal serial number inside sendCoins().
Thank you in advance.

Regards,
Alexis Azanza
![Screenshot 2020-11-12 at 12 57 54](https://user-images.githubusercontent.com/54721611/98931464-bb657a80-24e6-11eb-8f52-32eff6146646.png)
![Screenshot 2020-11-12 at 12 21 19](https://user-images.githubusercontent.com/54721611/98931195-675a9600-24e6-11eb-81ab-93b6a3450dbb.png)
![Screenshot 2020-11-12 at 12 40 15](https://user-images.githubusercontent.com/54721611/98931206-688bc300-24e6-11eb-94c3-c424f4edfc87.png)
![Screenshot 2020-11-12 at 12 40 28](https://user-images.githubusercontent.com/54721611/98931212-69bcf000-24e6-11eb-951f-961d01ad0930.png)
![Screenshot 2020-11-12 at 12 54 02](https://user-images.githubusercontent.com/54721611/98931242-6fb2d100-24e6-11eb-87c5-4decefc2e475.png)

**Comment by generalbytes** [comment]
Are you sure that you are calling IExtensionContext.addTransactionListener to actually register listener for being called.
See https://github.com/GENERALBYTESCOM/batm_public/blob/1bc688f86c1897fd82596dc6317fb2713bdd221b/server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/examples/TransactionExtension.java#L41

**Comment by alexisdevtailor** [comment]
No worries, I think I found the answer. I forgot to call addTransactionListener. I will give this a try.
Thanks. 

![Uploading Screenshot 2020-11-12 at 13.14.08.png…]()
