### ISSUE TITLE
Question about calculateCashAvailableForSell function

### ISSUE THREAD

**Issue by makarid** [GENERALBYTESCOM/batm_public#454]
Hello, i would like to ask you about this function. If i send a sellCrypto request for 100 euro, but i don't send the funds, does this function adds these 100 euro on the reserved pile even if i didn't send the funds yet? Thank you

**Comment by generalbytes** [comment]
Yes, 100 EUR is reserved in the machine's cassette ready for dissension.
How ever if user doesn't send BTC in time within a timeout that is defined in crypto settings (for example 45mins) the banknotes are no longer reserved.

**Comment by makarid** [comment]
OK, but when i call getCashAvailable, i don't get the available cash reduced by the waiting transaction to be filled.

**Comment by generalbytes** [comment]
I will get that checked with our developer.

**Comment by makarid** [comment]
Thank you. I am waiting.

**Comment by makarid** [comment]
Hello, i talked with my partner. No need to fix this. Thanks
