### ISSUE TITLE
IExtensionContext findAllTerminals() in extension init

### ISSUE THREAD

**Issue by raluik** [GENERALBYTESCOM/batm_public#468]
Hello,

We tried to call `ctx.findAllTerminals()` in extension init to compare the terminals to the one's in our db, but from the master logs we can see that the JDBC driver URL is null and a MYSQL NullPointerException was thrown.

We assume that it is too early at this stage to call this method. If that's the case, is there any alternative/workaround to this?

**Comment by generalbytes** [comment]
In newer version we will call init after database connection is established. That is proper solution.

**Comment by generalbytes** [comment]
This issue is fixed in server version 20210113.
