### ISSUE TITLE
findTerminalBySerialNumber function doesn't return correct status of terminal

### ISSUE THREAD

**Issue by makarid** [GENERALBYTESCOM/batm_public#475]
Hello, i have called the above function on 2 terminals, the one is online and functional and the other is offline. On both request i get 
{"locked":false,"active":true}. Why i get active = true on the terminal that is offline? Thank you

**Comment by generalbytes** [comment]
There is no attribute to signalize whether the machine is offline or online. When 'active' is true means that terminal is marked on server to allow customer transactions. You may want to explore ITerminal.getLastPingAt() method and compare it with current time to decide that machine is online.
