### ISSUE TITLE
getIdentityRemainingLimits sell_ct property returns null

### ISSUE THREAD

**Issue by makarid** [GENERALBYTESCOM/batm_public#478]
Hello, i would like to ask you about the sell_ct property on the IRemainingLimit. I have create a new Identity and have never done any transaction. I am calling the getIdentityRemainingLimits function in order to know how much limit has left for this identity. In order to do that i save the response of the sell_ct property. This property returns null for my identity. Why is that? Does the sell_ct property represents the available limit the specific identity has? What exactly this sell_ct represents? I want to check if the identity has available limits to do a transaction, do i need to compare the amount with sell_ct response only or i must do it for every limit return property( limitPerTransaction,perDay,month etc) Thanks

**Comment by pvyhnal-generalbytes** [comment]
Hi, 
`sell_ct` is just one of the configured values (Total identity cash limit) and not a computed or selected limit that will be used.

![Screenshot from 2021-01-26 10-48-33](https://user-images.githubusercontent.com/44365000/105832421-390a3400-5fc8-11eb-87f2-dfb780fc5b4f.png)

`null` would mean no limit configured (i.e. unlimited)

The effective limit you were probably looking for was missing and I added it in #481 (but it will require one of the future versions of the server), it will be available as `sell_resulting_limit`

**Comment by makarid** [comment]
When i am adding a new identity via the extensions, it is no possible to add this sell_ct. It has only txLimit,hourLimit,dayLimit,weekLimit,monthLimit. How can i add this limit? Also, how can i get the effective available limit of a specific identity in order to know that this identity has the limit to do an action? Thanks

**Comment by pvyhnal-generalbytes** [comment]
Do you need to be able to set "Total identity cash limit" from an extension for your use case? We would need to add that too.

> how can i get the effective available limit of a specific identity in order to know that this identity has the limit to do an action? Is there a computed limit that you compute with all the limits(tx,hour,day etc)? 

That is what will be added in the linked PR (when the server part is updated too)

**Comment by makarid** [comment]
> Do you need to be able to set "Total identity cash limit" from an extension for your use case? We would need to add that too.
> 
> > how can i get the effective available limit of a specific identity in order to know that this identity has the limit to do an action? Is there a computed limit that you compute with all the limits(tx,hour,day etc)?
> 
> That is what will be added in the linked PR (when the server part is updated too)

I just need to get a return value that will count all the basic limits an identity has(tx,hour,day,week,month) and return me the available limit to make the transaction. For example lets say that limit per tx is 1000 euro and perDay is 1500 euro. Lets say that an identity wants to make the first transaction of the day for 1500 euro. When i call this remainingLimit value i want to return me  1000 euro because the limitPerTx is 1000 euro. Next if he will try to make a second tx in the same day, when i call this remainingLimit value i want to return me 500 euro because the limit per day is 1500, he has already made 1000 euro, so 500 remainingLimit left. You got my point

**Comment by pvyhnal-generalbytes** [comment]
yes, that should be the `resulting_limit` that was added in the linked PR. It will be available in the next version or the following one

**Comment by makarid** [comment]
Great.Thanks!

**Comment by generalbytes** [comment]
Fixed in server release 20210127+
