### ISSUE TITLE
Adding 3rd party dependencies

### ISSUE THREAD

**Issue by raluik** [GENERALBYTESCOM/batm_public#485]
Hello,

How should one add 3rd party dependencies? Adding it to the server_extensions_extra build.gradle file doesn't make it accessible during runtime, throws a ClassNotFoundException.

**Comment by pvyhnal-generalbytes** [comment]
Hi, during release build the server_extensions_extra dependencies are copied into `/batm/app/master/lib/` directory. Would it resolve your issue if you copy your newly added dependencies there yourself during development?

**Comment by raluik** [comment]
Didn't work. Also our cryptocurrency is not open source.

**Comment by raluik** [comment]
Got it working by adding the desired dependency with it's transitive dependencies to the aforemenchioned directory
