### ISSUE TITLE
No Value present when i iterate getIdentityRemainingLimits response for resulting_limit

### ISSUE THREAD

**Issue by makarid** [GENERALBYTESCOM/batm_public#502]
Hello, in your new version 20210128 you are writing that you have include a new field on the IRemainingLimit interface,named resulting_limit. When i trying to find this specific type("resulting_limit") i got no value exception. Here is my code:

`List<IRemainingLimit> remainingLimits = context.getIdentityRemainingLimits(fiatCurrency, terminalNumber, identityPublicId);

BigDecimal remainingLimit = remainingLimits.stream().filter(iRemainingLimit -> iRemainingLimit.getLimitType().equals("resulting_limit")).findFirst().get().getAmount();`

**Comment by pvyhnal-generalbytes** [comment]
Hi, it should have "buy_" or "sell_" prefix. You can try listing all of them to see what is included.

**Comment by makarid** [comment]
I only get the following responses:


02/10/2021 04:23:12 PM | INFO | [»/VS-UNKNOWN/110] org.bitcoinmat.RESTSecuredService - buy_cp12m - 1000.0000000000
-- | -- | --
02/10/2021 04:23:12 PM | INFO | [»/VS-UNKNOWN/110] org.bitcoinmat.RESTSecuredService - buy_cp3m - 1000.0000000000
02/10/2021 04:23:12 PM | INFO | [»/VS-UNKNOWN/110] org.bitcoinmat.RESTSecuredService - buy_cpd - 1000.0000000000
02/10/2021 04:23:12 PM | INFO | [»/VS-UNKNOWN/110] org.bitcoinmat.RESTSecuredService - buy_cpdt - 1000.0000000000
02/10/2021 04:23:12 PM | INFO | [»/VS-UNKNOWN/110] org.bitcoinmat.RESTSecuredService - buy_cph - 1000.0000000000
02/10/2021 04:23:12 PM | INFO | [»/VS-UNKNOWN/110] org.bitcoinmat.RESTSecuredService - buy_cpm - 1000.0000000000
02/10/2021 04:23:12 PM | INFO | [»/VS-UNKNOWN/110] org.bitcoinmat.RESTSecuredService - buy_cpq - 1000.0000000000
02/10/2021 04:23:12 PM | INFO | [»/VS-UNKNOWN/110] org.bitcoinmat.RESTSecuredService - buy_cptr - 1000.0000000000
02/10/2021 04:23:12 PM | INFO | [»/VS-UNKNOWN/110] org.bitcoinmat.RESTSecuredService - buy_cpw - 1000.0000000000
02/10/2021 04:23:12 PM | INFO | [»/VS-UNKNOWN/110] org.bitcoinmat.RESTSecuredService - buy_cpy - 1000.0000000000
02/10/2021 04:23:12 PM | INFO | [»/VS-UNKNOWN/110] org.bitcoinmat.RESTSecuredService - buy_ct - 1000.0000000000
02/10/2021 04:23:12 PM | INFO | [»/VS-UNKNOWN/110] org.bitcoinmat.RESTSecuredService - sell_cp12m - 875.0000000000
02/10/2021 04:23:12 PM | INFO | [»/VS-UNKNOWN/110] org.bitcoinmat.RESTSecuredService - sell_cp3m - 1000.0000000000
02/10/2021 04:23:12 PM | INFO | [»/VS-UNKNOWN/110] org.bitcoinmat.RESTSecuredService - sell_cpd - 1000.0000000000
02/10/2021 04:23:12 PM | INFO | [»/VS-UNKNOWN/110] org.bitcoinmat.RESTSecuredService - sell_cpdt - 1000.0000000000
02/10/2021 04:23:12 PM | INFO | [»/VS-UNKNOWN/110] org.bitcoinmat.RESTSecuredService - sell_cph - 1000.0000000000
02/10/2021 04:23:12 PM | INFO | [»/VS-UNKNOWN/110] org.bitcoinmat.RESTSecuredService - sell_cpm - 1000.0000000000
02/10/2021 04:23:12 PM | INFO | [»/VS-UNKNOWN/110] org.bitcoinmat.RESTSecuredService - sell_cpq - 875.0000000000
02/10/2021 04:23:12 PM | INFO | [»/VS-UNKNOWN/110] org.bitcoinmat.RESTSecuredService - sell_cptr - 1000.0000000000
02/10/2021 04:23:12 PM | INFO | [»/VS-UNKNOWN/110] org.bitcoinmat.RESTSecuredService - sell_cpw - 1000.0000000000
02/10/2021 04:23:12 PM | INFO | [»/VS-UNKNOWN/110] org.bitcoinmat.RESTSecuredService - sell_cpy - 1000.0000000000
02/10/2021 04:23:12 PM | INFO | [»/VS-UNKNOWN/110] org.bitcoinmat.RESTSecuredService - sell_ct - 875.0000000000

**Comment by makarid** [comment]
> Hi, it should have "buy_" or "sell_" prefix. You can try listing all of them to see what is included.

Can you please add the correct type on your comments, because it is confusing.

**Comment by makarid** [comment]
The response is the same as it was before your update

**Comment by makarid** [comment]
Can someone help me understand what is going on here? Thanks

**Comment by makarid** [comment]
> Hi, it should have "buy_" or "sell_" prefix. You can try listing all of them to see what is included.

Is it possible to find a solution in this issue? Thanks

**Comment by makarid** [comment]
Can you please tell me if you have correctly added the new valueType on your server? I am waiting for your response.Thanks

**Comment by makarid** [comment]
@pvyhnal-generalbytes , any news please?

**Comment by pvyhnal-generalbytes** [comment]
Hi, sorry for the delay. I tried calling the `context.getIdentityRemainingLimits(fiatCurrency, terminalNumber, identityPublicId);` method and it is working for me. When calling the method, it should log something like below, the RESULTING LIMIT is the value that is returned as limitType `buy_resulting_limit` or `sell_resulting_limit`.

Could you please try again with the latest version?

![image](https://user-images.githubusercontent.com/44365000/110105439-ac158000-7da8-11eb-95ed-4497c1db0718.png)


```
2021-03-05 11:43:45.258 [»/Master-start/1] DEBUG batm.common.TransactionLimits - Buy Transaction Limits (BT399999, identity = IARBE74KKS7YHP88 [1], cryptoAddress = null):
	entry_cptr = 9,999,999.00 CZK | result_cptr = 9,999,999.00 CZK (Limit per Transaction)
	entry_cph = 88,888.00 CZK | cashInLastHour = 0.00 CZK | result_cph = 88,888.00 CZK (Limit per hour)
	entry_cpd = Not Set | cashInDay = 0.00 CZK | result_cpd = No Limit (Limit per day)
	entry_cpda = Not Set | cashInDayForAddress = 0.00 CZK | result_cpda = No Limit (Limit per day for address)
	entry_cpdt = 88,888.00 CZK | cashInDayForTerminal = 0.00 CZK | result_cpdt = 88,888.00 CZK (Limit per day for Terminal)
	entry_cpw = Not Set | cashInWeek = 0.00 CZK | result_cpw = No Limit (Limit per week)
	entry_cpm = Not Set | cashInMonth = 100.00 CZK | result_cpm = No Limit (Limit per month)
	entry_cp3m = Not Set | cashIn3Month = 100.00 CZK | result_cp3m = No Limit (Limit per 3 months)
	entry_cp12m = Not Set | cashIn12Month = 100.00 CZK | result_cp12m = No Limit (Limit per 12 months)
	entry_cpq = Not Set | cashInQuarter = 100.00 CZK | result_cpq = No Limit (Limit per calendar year quarter)
	entry_cpy = Not Set | cashInYear = 100.00 CZK | result_cpy = No Limit (Limit per calendar year)
	entry_ctpa = Not Set | cashTotalPerAddress = 0.00 CZK | result_ctpa = No Limit (Total cash limit per crypto address)
	entry_ct = Not Set | cashTotal = 100.00 CZK | result_ct = No Limit (Total Identity Limit)
	RESULTING LIMIT = 88,888.00 CZK [Limit per hour]
2021-03-05 11:43:45.406 [»/Master-start/1] DEBUG batm.common.TransactionLimits - Sell Transaction Limits (BT399999, identity = IARBE74KKS7YHP88 [1], cryptoAddress = null):
	entry_cptr = 9,999,999.00 CZK | result_cptr = 9,999,999.00 CZK (Limit per Transaction)
	entry_cph = 88,888.00 CZK | cashInLastHour = 0.00 CZK | result_cph = 88,888.00 CZK (Limit per hour)
	entry_cpd = Not Set | cashInDay = 0.00 CZK | result_cpd = No Limit (Limit per day)
	entry_cpda = Not Set | cashInDayForAddress = 0.00 CZK | result_cpda = No Limit (Limit per day for address)
	entry_cpdt = 77,777.00 CZK | cashInDayForTerminal = 0.00 CZK | result_cpdt = 77,777.00 CZK (Limit per day for Terminal)
	entry_cpw = Not Set | cashInWeek = 0.00 CZK | result_cpw = No Limit (Limit per week)
	entry_cpm = Not Set | cashInMonth = 0.00 CZK | result_cpm = No Limit (Limit per month)
	entry_cp3m = Not Set | cashIn3Month = 0.00 CZK | result_cp3m = No Limit (Limit per 3 months)
	entry_cp12m = Not Set | cashIn12Month = 0.00 CZK | result_cp12m = No Limit (Limit per 12 months)
	entry_cpq = Not Set | cashInQuarter = 0.00 CZK | result_cpq = No Limit (Limit per calendar year quarter)
	entry_cpy = Not Set | cashInYear = 0.00 CZK | result_cpy = No Limit (Limit per calendar year)
	entry_ctpa = Not Set | cashTotalPerAddress = 0.00 CZK | result_ctpa = No Limit (Total cash limit per crypto address)
	entry_ct = Not Set | cashTotal = 0.00 CZK | result_ct = No Limit (Total Identity Limit)
	RESULTING LIMIT = 77,777.00 CZK [Sell limit per day for Terminal]
```

**Comment by makarid** [comment]
After i upgraded the server to 20210301, i also see it myself. Thank you
