### ISSUE TITLE
Price quote to an exchange

### ISSUE THREAD

**Issue by voidhole** [GENERALBYTESCOM/batm_public#510]
Hello,

We would like to make a request to get BTC/HKD price from tidebit.com

The below is sample Javascript thkx

  return axios.get('https://www.tidebit.com/api/v2/tickers.json')
  .then(r => {
    const data = r.data
    const askprice = BN(data.btchkd.ticker.sell)
    const bidprice = BN(data.btchkd.ticker.buy)

**Comment by voidhole** [comment]
and they might have block IP if use for long time so would be great if we can input proxies

**Comment by generalbytes** [comment]
Please open different ticket and ask there proper question that relates to GB product.
