### ISSUE TITLE
Buy

### ISSUE THREAD

**Issue by informationman007** [GENERALBYTESCOM/batm_public#516]
We need direction on using JSON to buy. I assume they have a more complete api reference.
Befimov@cpscorporate.com

**Comment by pvyhnal-generalbytes** [comment]
Hi, you could implement your extension that would call the `IExtensionContext.buyCrypto` method, see https://github.com/GENERALBYTESCOM/batm_public/blob/077abebf50b3d23ccb93a7775a9aff2d6f494891/server_extensions_api/src/main/java/com/generalbytes/batm/server/extensions/IExtensionContext.java#L344

For example use see https://github.com/GENERALBYTESCOM/batm_public/blob/077abebf50b3d23ccb93a7775a9aff2d6f494891/server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/examples/rest/RESTServiceExample.java#L174

**Comment by informationman007** [comment]
Thank you very much for your response.
We will review and follow up ASAP.

Kind regards,
B
