### ISSUE TITLE
API endpoint to connect with url or postman or express to get data for transactions on my terminals 

### ISSUE THREAD

**Issue by nowfms** [GENERALBYTESCOM/batm_public#518]
I’ve had a look through your github but I am finding it difficult to find an API endpoint which I can connect to with cURL or postman or Express.
 
Is there an endpoint (for example https://api.batm.com/{id}) / API documentation that I can be pointed to which will allow me to send GET requests to the API to receive data about transactions customers make at the BATMs I have installed?
 
Any extra information would be much appreciated.

**Comment by pvyhnal-generalbytes** [comment]
Hi, we don't have such API available but if you run your own installation of the server you could implement an extension that runs in the server and can access for example information about existing transactions.
Please see 
https://github.com/GENERALBYTESCOM/batm_public/blob/master/README.md

and methods on the IExtensionContext interface such as: 

https://github.com/GENERALBYTESCOM/batm_public/blob/077abebf50b3d23ccb93a7775a9aff2d6f494891/server_extensions_api/src/main/java/com/generalbytes/batm/server/extensions/IExtensionContext.java#L87

**Comment by generalbytes** [comment]
See REST examples to have idea how to connect to Java API with REST. 
https://github.com/GENERALBYTESCOM/batm_public/tree/master/server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/examples/rest

**Comment by mxicodersplind** [comment]
> See REST examples to have idea how to connect to Java API with REST. https://github.com/GENERALBYTESCOM/batm_public/tree/master/server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/examples/rest

I tried to call this rest api examples but it is giving 404, why ?
