### ISSUE TITLE
[Email] Is there a way to change email sender properties

### ISSUE THREAD

**Issue by makarid** [GENERALBYTESCOM/batm_public#530]
Hello, i would like to ask you if there a way to change the email properties on sendAsync email functions on the Extensions. Right every email has this email as sender mgun.generalbytes.com. I think that this is a security risk for phishing attempts. Is there a way to put our companies email provider info using a properties file or something? Thanks

**Comment by generalbytes** [comment]
Please contact support@generalbytes.com
