### ISSUE TITLE
findIdentityByPhoneNumber returns a List of IIdentity, why?

### ISSUE THREAD

**Issue by bitcoinmat-dev** [GENERALBYTESCOM/batm_public#533]
Hello, you have the following 2 functions:

1) findIdentitiesByPhoneNumber => List of IIdentity
2) findIdentityByPhoneNumber => List of IIdentity

My question is why you return a List in the second one? I think that you have implement a check in order to prevent duplication of phoneNumbers in identities. Thanks for your response.

**Comment by bitcoinmat-dev** [comment]
Any response here please. Thanks

**Comment by generalbytes** [comment]
There can be multiple identities with same phone number when customer registers on 2 or more ATMs where each ATM is present in more organizations.
