### ISSUE TITLE
[»/VS-UNKNOWN/149] batm.master.APIExceptionMapper - Error java.lang.NoSuchMethodError: com.generalbytes.batm.server.extensions.IExtensionContext.updateIdentity(Ljava/lang/String;Ljava/lang/String;IILjava/util/Date;Ljava/util/Date;Ljava/math/BigDecimal;Ljava/math/BigDecimal;Ljava/lang/String;Ljava/util/List;Ljava/util/List;Ljava/util/List;Ljava/util/List;)Lcom/generalbytes/batm/server/extensions/IIdentity;

### ISSUE THREAD

**Issue by bitcoinmat-dev** [GENERALBYTESCOM/batm_public#541]
Hello, i am getting NoSuchMethodError on updateIdentity. Server version 20210415

**Comment by generalbytes** [comment]
Try server version 20210427.

**Comment by bitcoinmat-dev** [comment]
The same error

**Comment by generalbytes** [comment]
Your extension is most likely compiled against old extensions api missing last parameter of updateIdentity method.
See current version here:
https://github.com/GENERALBYTESCOM/batm_public/blob/05527d9341796bebd2d6a53220f9d5ceec88f116/server_extensions_api/src/main/java/com/generalbytes/batm/server/extensions/IExtensionContext.java#L212
