### ISSUE TITLE
[Question] About Allocated icon using extensions sellCrypto function

### ISSUE THREAD

**Issue by makarid** [GENERALBYTESCOM/batm_public#548]
Hello, i am using sellCrypto function using extensions and i am having the following issue. Even thought the withdraw process works, the "A" icon on the transaction list never becomes green, it is always grey. This happens only when i am creating a transaction using extensions. Is this the correct behavior? I am waiting for your response.Thanks

**Comment by pvyhnal-generalbytes** [comment]
- what is your Withdrawal Strategy in Crypto Settings -> Sell?
- what Status is the transaction in at the Transactions page?


For me when I create a transaction from an extension and it is in PAYMENT REQUESTED the "A" icon is green

You can have a look at `findTerminalsWithAvailableCashForSell` or `getCashBoxes` methods to see if it is helpful for your use case

**Comment by pvyhnal-generalbytes** [comment]
[GB-5861]

**Comment by makarid** [comment]
My Sell strategy is 3. Receive coins in Exchange.
The transaction is completed.

**Comment by makarid** [comment]
Hello again,

i am trying to simulate a payment arrived for a transaction but when i press the button, the W letter is becomes GREEN and the terminal saying that the ticket has already been redeemed.

**Comment by pvyhnal-generalbytes** [comment]
you can set `transactionrecord.withdrawn` and `transactionrecord.canbecashedout` in your database, but only use that for development testing

**Comment by makarid** [comment]
Thank you very much for this info!!!

Στις Παρ, 11 Ιουν 2021 στις 1:24 μ.μ., ο/η Premek ***@***.***>
έγραψε:
