### ISSUE TITLE
Technical Discussion Requested?

### ISSUE THREAD

**Issue by aphilip-om** [GENERALBYTESCOM/batm_public#551]
Good Afternoon 

We are working with a company (Delta Business Management) which is using your BAT-4 ATMs.

We would like the machines to interact with a specific platform which we developed and would like to have a private discussion to expose our system and requirements in more details. 

Please can you let me know how this can be facilitated?

Thanks 

Mike @ Tap Global

**Comment by generalbytes** [comment]
Best would be to have the Delta Business Management representative to contact support@generalbytes.com and ask for a paid consultation.
