### ISSUE TITLE
[Question] About LimitCashTotalIdentity

### ISSUE THREAD

**Issue by makarid** [GENERALBYTESCOM/batm_public#552]
Hello, i would like to ask you about this limit. What does this mean represents? Is the maximum amount of trades that the user can make or something else? Also, if i try to update an identity what will happen if i just put null on this field?
Can you please add more info on the comments section of the classes, it is very difficult to understand how the inner system works. I am waiting for your response. Thanks

**Comment by generalbytes** [comment]
LimitCashTotalIdentity = You can set a total limit of how much cash identity can insert into the machines over the lifetime of the server.
I also created this ticket:
https://generalbytes.atlassian.net/browse/BPUB-1629
