### ISSUE TITLE
[Question] About URI that the Redeem Ticket button needs to scan the QRcode correctly

### ISSUE THREAD

**Issue by makarid** [GENERALBYTESCOM/batm_public#554]
Hello, can you please tell me what parameters i must put on a bitcoin URI in order the Redeem Ticket to scan it correctly?
Thanks

**Comment by pvyhnal-generalbytes** [comment]
The format of the QR code on the sell tickets printed from the ATM is following. 
You can also scan a ticket from your ATM for an example

`bitcoin:<crypto-address>?amount=<crypto-amount>&label=<transaction-remote-id>&uuid=<UUID>`

**Comment by makarid** [comment]
I am using this format but even though i can see the spinner on the screen, nothing happens
