### ISSUE TITLE
ETC - support buy/sell

### ISSUE THREAD

**Issue by StaticSpark** [GENERALBYTESCOM/batm_public#566]
Support for ethereum classic is missing.

Transfer fees are very low, in fact 50% of etc market cap is moved on the daily which makes this a great base layer coin, similar to bitcoin..

Seems like the web3j plugin should work now for classic. Ethereum Classic team made updates to web development.
https://twitter.com/Mantis_IO/status/1408470201113485314
https://docs.mantisclient.io/how-tos/how-to-use-web3-js-with-Mantis-client

One might be able to extend the erc20 code in ethereum extension and just update the network numbers, or Chain id. 
  - with the BIP-44 [Coin Index 61 and EVM Chain ID 61](https://en.wikipedia.org/wiki/Ethereum_Classic)

**Comment by pvyhnal-generalbytes** [comment]
ETC support was added in version 20210316

**Comment by StaticSpark** [comment]
Oh, I'll ask support to update the website for BATM 4 and Ethereum Classic. <3
