### ISSUE TITLE
Need Assistance setting up BATM This week

### ISSUE THREAD

**Issue by alc9087** [GENERALBYTESCOM/batm_public#60]
I am searching for a developer that will help me setup my BATM Machine this week sometime.

**Comment by rudygodoy** [comment]
You don't necessarily need a developer, unless you plan to do some customizations to the CAS. Happy to help here.

**Comment by generalbytes** [comment]
Please use official support on support@generalbytes.com

**Comment by rpanak-generalbytes** [comment]
This is a support issue, please use the appropriate support channels as stated in previous comment.
Closing.
