### ISSUE TITLE
Issue when identities have notes

### ISSUE THREAD

**Issue by pedroguima** [GENERALBYTESCOM/batm_public#671]
Whenever I use the API to search for identities (using the search for phone number or for ID examples), I get this on the stack trace **if any user has a note** (even if that's not the one being searched):

`java.lang.ClassCastException: class com.generalbytes.batm.server.extensions.a.a.i cannot be cast to class com.generalbytes.batm.server.extensions.IIdentityNote (com.generalbytes.batm.server.extensions.a.a.i and com.generalbytes.batm.server.extensions.IIdentityNote are in unnamed module of loader 'app')`

It works fine if no identities have notes.

Could you please advise?

Thanks

**Comment by pedroguima** [comment]
I'm using the latest stable version of master and admin

**Comment by pvyhnal-generalbytes** [comment]
Hi, 
- are you running batm server version 20211102? Could you try to update your server using `batm-manage` to the same version (20211102) again to make sure you have the latest patch version?
- Could you try to recompile your extension in a way that is is based on tag **1.0.40.2** of this repository? https://github.com/GENERALBYTESCOM/batm_public/tree/1.0.40.2 and let us know if the problem persists?

**Comment by pedroguima** [comment]
Hello @pvyhnal-generalbytes,

Thanks for the quick response.

I'm using version 20211102 and updating server_extensions_api to that patch didn't help.

Could you please advise?

Thanks

**Comment by pvyhnal-generalbytes** [comment]
Could you please describe the extension you are developing in more detail? Is it based on server_extensions_extra? If yes, could you alse rebase it on the tag version above? What method are you calling exactly when you get the exception? We will try to reproduce the issue you are having but please allow for some delay due to the holiday, thank you

**Comment by pedroguima** [comment]
Hello @pvyhnal-generalbytes ,

It is based on `server_extensions_extra` and it has been rebased as well. 

I implemented the `/register` and `/find-identities-by-phone-number` endpoints successfully and they work fine.  Issue is, whenever a `note` is added to **any** identity, I can't search for identities any more using the API.

The issue is in com.generalbytes.batm.server.extensions.a.a, class "IdentityNote", I believe. I guess there's a method there to retrieve notes for an Identity where a variable is not casted properly.

Please find the stack trace below for findIdentitiesByPhoneNumber example:

`java.lang.ClassCastException: class com.generalbytes.batm.server.extensions.a.a.i cannot be cast to class com.generalbytes.batm.server.extensions.IIdentityNote (com.generalbytes.batm.server.extensions.a.a.i and com.generalbytes.batm.server.extensions.IIdentityNote are in unnamed module of loader 'app')
	at com.generalbytes.batm.server.extensions.a.a.i.a(GB:26)
	at com.generalbytes.batm.server.extensions.a.a.h.a(GB:257)
	at com.generalbytes.batm.server.extensions.a.a.a(GB:1032)
	at com.generalbytes.batm.server.extensions.a.a.d(GB:999)
	at com.generalbytes.batm.server.extensions.f.findIdentitiesByPhoneNumber(GB:743)
	at com.generalbytes.batm.server.extensions.mindthecoin.identity.IdentityRestService.register(IdentityRestService.java:242)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
`

Is there a way to adapt IIdentityNote on my side to avoid this?

**Comment by pedroguima** [comment]
Hello,

Any news on this one?

Thanks

**Comment by pedroguima** [comment]
Hi @mmyslivec-GB, @pvyhnal-generalbytes @generalbytes,

Any ideas on this one?

I tried to change IIdentityNote but not luck. Feels like there's a method/var missing from the interface.

Could you please advise?

Thanks

**Comment by pedroguima** [comment]
Fixed on version 20211122
