### ISSUE TITLE
Problem Error 1091 (42000) at line 1: Can't DROP .... in last version 20180528

### ISSUE THREAD

**Issue by darkban** [GENERALBYTESCOM/batm_public#68]
the new update 20180528 generate this error whenever the command is started all services on the digitalocean

![error new version](https://user-images.githubusercontent.com/32014414/40630531-9af3b99c-62d3-11e8-884a-8bd5c46cb4c0.png)

**Comment by rpanak-generalbytes** [comment]
This has been fixed already. Don't worry, you can safely ignore the message and the server works as expected.
