### ISSUE TITLE
How we can call the api endpoints and how we can confirm that our master service is working properly.

### ISSUE THREAD

**Issue by mxicodersplind** [GENERALBYTESCOM/batm_public#739]
We installed our own server in that we cloned from this repo and tried to call the api endpoints described in the REST examples like for ex:- https://publicip:7743/extensions/example/terminals.
but that doesn't work when we checked that on port 7743 nothing is running but in our batm info both master and admin service was shown as running
so this is the fault of port or i am missing something here if needed any other info please comment down i will immediately provide.
Thank You

**Comment by pvyhnal-generalbytes** [comment]
The example extensions are not loaded by default, see  autoload="false"  in batm-extensions.xml

**Comment by mxicodersplind** [comment]
> The example extensions are not loaded by default, see autoload="false" in batm-extensions.xml

yes i changed all to true then clean the build, again built the build but still i am facing curl: (7) Failed to connect to port 7743: Connection refused.
