### ISSUE TITLE
Master service is not working after copying batm_server_extensions_extra.jar

### ISSUE THREAD

**Issue by mxicodersplind** [GENERALBYTESCOM/batm_public#743]
i) I Added new crypto currency i renamed currencies jar to currencies-1.0.XX.SNAPSHOT.jar and copied it to /batm/app/master/lib/
ii) Then i added its logo images in resources and then i added fix price RateSource and added demo wallet and demo exchange
iii) Then i added its extension in batm-extensions.xml
iv)Then i created a build and then i copied batm_server_extensions_extra.jar to /batm/app/master/extension/ directory and also tried with replacing server_extensions_extra-1.0.56.3.jar
v)Then i changed its owner/group type from root  to "batm".
vi) And also tried after putting it in batm/app/master/lib/  Directory
After trying this things everytime i am facing same problem which is stuck on waiting for master to start up u can also find it in Below.
So, Please help me what is the solution should i have to copy batm_server_extensions_extra.jar or replace with server_extensions_extra-1.0.56.3.jar inside batm/app/master/extensions/ 
and what extra step i have to do?

![Screenshot (443)](https://user-images.githubusercontent.com/80950554/182815555-ae493cd7-a763-4a99-8b2c-0803b503d398.png)

**Comment by GB-Martin** [comment]
Hello mxicodersplind,

Regarding i) → customers are not allowed to modify CAS source files. You can only edit within extensions. Due to that, your changes are causing the mentioned behavior.

Thank you for your understanding. Best regards,
Martin
GB support department

**Comment by mxicodersplind** [comment]
Ok so did i replace the new currencies jar with the previous one or i have to copy new jar in the lib directory separately?
