### ISSUE TITLE
Buy Rate Source from CAS fails, but server is reached (works locally)

### ISSUE THREAD

**Issue by leocape** [GENERALBYTESCOM/batm_public#814]
I have added an extension for our exchange, and getting the buy rate source works locally and the BigDecimal rate is returned. 

However when testing from the CAS  we get: `Rate Source Buy test FAILED. Cannot instantiate rate source. Invalid parameters?`

We can see the logs on the exchange server showing that the request comes in fine and response is sent correctly with 200.

Parameter appears to be correct - using "ZAR" as the fiat currency (tried upper and lower case).

Testing with Binance also fails but with a different error `Rate Source Buy test FAILED. Cannot obtain rate. Invalid parameters?`

Nothing relevant appears to be showing in the logs.

Any ideas of what to try / diagnose?

PS Do we need to add a custom rate source/ folder explicitly? - we're assuming it uses the method `getExchangeRateForBuy()` in the Exchange.java file ie we have not created a entirely separate rate source for the exchange. Do we need to do this?

Thanks

**Comment by generalbytes** [comment]
Please contact support@generalbytes.com. This is not a place for tech support questions. Tech support will ask you for the master.log which should explain behavior that you are experiencing.
